### ISSUE TITLE
Load VideoChat error

### ISSUE THREAD

**Issue by LixiangHello** [OpenGVLab/Ask-Anything#101]
Load VideoChat from: weights/videochat.pth
Traceback (most recent call last):
  File "demo.py", line 179, in <module>
    chat = init_model()
  File "demo.py", line 20, in init_model
    model = VideoChat(config=cfg.model)
  File "/root/autodl-tmp/Ask-Anything/video_chat/models/videochat.py", line 142, in __init__
    msg = self.load_state_dict(ckpt['model'], strict=False)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VideoChat:
        size mismatch for llama_proj.weight: copying a param with shape torch.Size([5120, 768]) from checkpoint, the shape in current model is torch.Size([4096, 768]).
        size mismatch for llama_proj.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).

**Comment by yinanhe** [comment]
Please make sure the checkpoint you have downloaded is correct, or provide more information.

**Comment by yinanhe** [comment]
Due to lack of further information, this issue will be temporarily closed. Please feel free to reopen it at any time.
