### ISSUE TITLE
没看懂readme

### ISSUE THREAD

**Issue by 871052165** [OpenGVLab/Ask-Anything#105]
正在部署video_chat，但是在看readme时出现疑问，是要先下载llama-13b-hf再下载stable-vicuna-13b-delta，再进行数据处理，还是只需要下载stable-vicuna-13b-delta的权重文件进行配置就行

**Comment by yinanhe** [comment]
如果使用了stable-vicuna的话，是需要先下载llama-13b-hf再下载stable-vicuna-13b-delta，然后进行转换得到stable-vicuna-13b的权重
