### ISSUE TITLE
tutorial misleading

### ISSUE THREAD

**Issue by robotNo201** [OpenGVLab/Ask-Anything#110]
I wonder why we need to preprocess LLama. I know why preprocess vicuna, because we will change the directory in config.json and use it, but I dont see anything related to LLama in the tutorial, so why?

**Comment by Andy1621** [comment]
I don't understand your problem... If you mean how to run our model, we have provided `demo.ipynb`. If you mean how to run LLaMA or Vicuna, I suggest reading the tutorials on HuggingFace.
