### ISSUE TITLE
encode_img中的instruction作用

### ISSUE THREAD

**Issue by snowyrain** [OpenGVLab/Ask-Anything#114]
video_chat2中的videochat2_it.py代码里的 def encode_img(self, image, instruction)中的instruction的作用具体是什么？ [https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/models/videochat2_it.py#L174](url)

**Comment by Andy1621** [comment]
可以看看论文里videochat2 three-stage训练pipeline哈，这个instruction是在stage3时插入到QFormer中，辅助QFormer更好地获取所需要的上下文信息，从而提升LLM回复的效果

**Comment by Andy1621** [comment]
这个加不加都可以的，我们实验里加上效果会略好些

**Comment by dragen1860** [comment]
@Andy1621 hi, 但是我看demo里面，instruction是使用的通用的watch the video and answer the question. 为啥不让用户输入instruction呢？ 效果差异大吗？

**Comment by Andy1621** [comment]
可以自己做实验试试区别哈，当时做demo随意指定了一个instruction~

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
