### ISSUE TITLE
why VideoChat2 video encoder use UMT_L instead of ViClip?

### ISSUE THREAD

**Issue by dragen1860** [OpenGVLab/Ask-Anything#116]
hi, according to your paper, Viclip has higher accuracy and large-scale pretrained. Why did not use ViClip as VideoChat2's video encoder? thank you.

**Comment by shepnerd** [comment]
We had developed a ViCLIP-based VideoChat and plan to release it soon.
UMT outperformed ViCLIP in terms of video-text performance, thanks to the inclusion of video-text matching loss and other advanced techniques. In contrast, ViCLIP is solely trained using video-text contrastive loss, without additional enhancements. However, ViCLIP still achieved remarkable zero-shot action recognition and satisfactory video retrieval results.
