### ISSUE TITLE
Using UMT over ViClip

### ISSUE THREAD

**Issue by irwin-dt** [OpenGVLab/Ask-Anything#120]
Hi, I noticed that the main drawback of current VideoLLM's is that they tend to be limited to short videos. Could I check with you the intuition behind the choice of choosing UMT over ViClip has the visual encoder? Since ViClip is trained on videos that are much longer, I had thought that among your work, it would be prioritised over UMT.

Best Regards

**Comment by yinanhe** [comment]
This issue is very similar to https://github.com/OpenGVLab/Ask-Anything/issues/116#issuecomment-1916913558, you can refer to the answer here.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
