### ISSUE TITLE
Can VideoChat2  support LLAMA2?

### ISSUE THREAD

**Issue by idejie** [OpenGVLab/Ask-Anything#121]

**Comment by yinanhe** [comment]
To use llama2, you need to train video_chat2 based on stage1.

**Comment by yinanhe** [comment]
Yes, if you want to switch to any other LLM, you'll need to complete stages 2 and 3 of the training.

**Comment by yinanhe** [comment]
> btw, 我可以加一下微信群吗？readme中二维码过期了

可以的，您可以通过扫描小助手的微信二维码进1群（这个群会r热闹点） 或者通过这个二维码进2群
![image](https://github.com/OpenGVLab/Ask-Anything/assets/43169235/488b56f9-1ee0-4574-b921-6a1d3eb62b01)
