### ISSUE TITLE
what is the usage of buffer = vr.get_batch(index).asnumpy() when using decord to read frames?

### ISSUE THREAD

**Issue by dragen1860** [OpenGVLab/Ask-Anything#122]
<img width="1032" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/4252555/01df7401-6e5b-4649-b739-6816f70b05d8">

Dear all:
  the `buffer` is really confusing. anyone would kindly illustrate it?

**Comment by yinanhe** [comment]
To get multiple frames at once, use `get_batch` this is the efficient way to obtain a long list of frames.  Perhaps with `decord.bridge.set_bridge('torch')` could be a more efficient data pre-process method.

**Comment by dragen1860** [comment]
> To get multiple frames at once, use `get_batch` this is the efficient way to obtain a long list of frames. Perhaps with `decord.bridge.set_bridge('torch')` could be a more efficient data pre-process method.

hi, but my question is not `get_batch` to obtains several frames meanwhile. My question is: `buffer = vr.get_batch(index).asnumpy()` the buffer tensor is never used. why use `buffer` before `images_group`?

**Comment by yinanhe** [comment]
Sorry for just realizing that this was a duplicate block that wasn't removed during code cleanup. It has been corrected, and indeed, that data block wasn't utilized.

https://github.com/OpenGVLab/Ask-Anything/blob/d6ec28c157241867fcef80c44cdf4b732ca8b8ad/video_chat2/conversation.py#L96-L118

**Comment by dragen1860** [comment]
thanks for your responsible work.
