### ISSUE TITLE
Unexpected output with dummy characters

### ISSUE THREAD

**Issue by iambadbadboy** [OpenGVLab/Ask-Anything#123]
result:
<img width="899" alt="output" src="https://github.com/OpenGVLab/Ask-Anything/assets/158791909/43c9d904-bd11-4b2d-9e7e-31565c9bd846">

I follow the end2end tutorial, I downloaded Vit, QFormer with the provided wget command on tutorial, then I downloaded vicuna-7b-delta-v0 and process it with apply_delta.py, the following is the output folder:
<img width="341" alt="vicuna" src="https://github.com/OpenGVLab/Ask-Anything/assets/158791909/c2b01172-c3ba-4b04-98e3-82b3db96ae68">
So there should be no problem with the output folder, no worries on file corruption, all files downloaded and preprocessed pefectly.
And download the videochat_7b.pth as shown below
<img width="388" alt="videochat" src="https://github.com/OpenGVLab/Ask-Anything/assets/158791909/8507d502-9d19-4bd2-a759-d44d79fd134d">

Then i change the config_7b.json and cofig.json(just in case), 
<img width="291" alt="config" src="https://github.com/OpenGVLab/Ask-Anything/assets/158791909/dd6f9cc8-3b68-420e-9f22-7ebb4afbc491">
Also on the demo.py
<img width="616" alt="img1" src="https://github.com/OpenGVLab/Ask-Anything/assets/158791909/1b04dd27-dac7-49bc-a651-68ef64978f46">
All pth files are the exact files required to be downloaded
The environment is the requirements.txt, pip install with no errors.

Can someone gives me some hints where I did wrong? thx. I know the best guess is the missing weights, but these weight files are the ones in tutorial.

Below is the console message
 
Load ViT model from: model/eva_vit_g.pth
Inflate: patch_embed.proj.weight, torch.Size([1408, 3, 14, 14]) => torch.Size([1408, 3, 1, 14, 14])
Init center: True
_IncompatibleKeys(missing_keys=['gmhra_cls_token', 'gmhra.0.dpe.weight', 'gmhra.0.dpe.bias', 'gmhra.0.attn.in_proj_weight', 'gmhra.0.attn.in_proj_bias', 'gmhra.0.attn.out_proj.weight', 'gmhra.0.attn.out_proj.bias', 'gmhra.0.ln_1.weight', 'gmhra.0.ln_1.bias', 'gmhra.0.mlp.c_fc.weight', 'gmhra.0.mlp.c_fc.bias', 'gmhra.0.mlp.c_proj.weight', 'gmhra.0.mlp.c_proj.bias', 'gmhra.0.ln_2.weight', 'gmhra.0.ln_2.bias', 'gmhra.0.ln_3.weight', 'gmhra.0.ln_3.bias', 'gmhra.1.dpe.weight', 'gmhra.1.dpe.bias', 'gmhra.1.attn.in_proj_weight', 'gmhra.1.attn.in_proj_bias', 'gmhra.1.attn.out_proj.weight', 'gmhra.1.attn.out_proj.bias', 'gmhra.1.ln_1.weight', 'gmhra.1.ln_1.bias', 'gmhra.1.mlp.c_fc.weight', 'gmhra.1.mlp.c_fc.bias', 'gmhra.1.mlp.c_proj.weight', 'gmhra.1.mlp.c_proj.bias', 'gmhra.1.ln_2.weight', 'gmhra.1.ln_2.bias', 'gmhra.1.ln_3.weight', 'gmhra.1.ln_3.bias', 'gmhra.2.dpe.weight', 'gmhra.2.dpe.bias', 'gmhra.2.attn.in_proj_weight', 'gmhra.2.attn.in_proj_bias', 'gmhra.2.attn.out_proj.weight', 'gmhra.2.attn.out_proj.bias', 'gmhra.2.ln_1.weight', 'gmhra.2.ln_1.bias', 'gmhra.2.mlp.c_fc.weight', 'gmhra.2.mlp.c_fc.bias', 'gmhra.2.mlp.c_proj.weight', 'gmhra.2.mlp.c_proj.bias', 'gmhra.2.ln_2.weight', 'gmhra.2.ln_2.bias', 'gmhra.2.ln_3.weight', 'gmhra.2.ln_3.bias', 'gmhra.3.dpe.weight', 'gmhra.3.dpe.bias', 'gmhra.3.attn.in_proj_weight', 'gmhra.3.attn.in_proj_bias', 'gmhra.3.attn.out_proj.weight', 'gmhra.3.attn.out_proj.bias', 'gmhra.3.ln_1.weight', 'gmhra.3.ln_1.bias', 'gmhra.3.mlp.c_fc.weight', 'gmhra.3.mlp.c_fc.bias', 'gmhra.3.mlp.c_proj.weight', 'gmhra.3.mlp.c_proj.bias', 'gmhra.3.ln_2.weight', 'gmhra.3.ln_2.bias', 'gmhra.3.ln_3.weight', 'gmhra.3.ln_3.bias', 'gmhra.4.dpe.weight', 'gmhra.4.dpe.bias', 'gmhra.4.attn.in_proj_weight', 'gmhra.4.attn.in_proj_bias', 'gmhra.4.attn.out_proj.weight', 'gmhra.4.attn.out_proj.bias', 'gmhra.4.ln_1.weight', 'gmhra.4.ln_1.bias', 'gmhra.4.mlp.c_fc.weight', 'gmhra.4.mlp.c_fc.bias', 'gmhra.4.mlp.c_proj.weight', 'gmhra.4.mlp.c_proj.bias', 'gmhra.4.ln_2.weight', 'gmhra.4.ln_2.bias', 'gmhra.4.ln_3.weight', 'gmhra.4.ln_3.bias', 'gmhra.5.dpe.weight', 'gmhra.5.dpe.bias', 'gmhra.5.attn.in_proj_weight', 'gmhra.5.attn.in_proj_bias', 'gmhra.5.attn.out_proj.weight', 'gmhra.5.attn.out_proj.bias', 'gmhra.5.ln_1.weight', 'gmhra.5.ln_1.bias', 'gmhra.5.mlp.c_fc.weight', 'gmhra.5.mlp.c_fc.bias', 'gmhra.5.mlp.c_proj.weight', 'gmhra.5.mlp.c_proj.bias', 'gmhra.5.ln_2.weight', 'gmhra.5.ln_2.bias', 'gmhra.5.ln_3.weight', 'gmhra.5.ln_3.bias', 'gmhra.6.dpe.weight', 'gmhra.6.dpe.bias', 'gmhra.6.attn.in_proj_weight', 'gmhra.6.attn.in_proj_bias', 'gmhra.6.attn.out_proj.weight', 'gmhra.6.attn.out_proj.bias', 'gmhra.6.ln_1.weight', 'gmhra.6.ln_1.bias', 'gmhra.6.mlp.c_fc.weight', 'gmhra.6.mlp.c_fc.bias', 'gmhra.6.mlp.c_proj.weight', 'gmhra.6.mlp.c_proj.bias', 'gmhra.6.ln_2.weight', 'gmhra.6.ln_2.bias', 'gmhra.6.ln_3.weight', 'gmhra.6.ln_3.bias', 'gmhra.7.dpe.weight', 'gmhra.7.dpe.bias', 'gmhra.7.attn.in_proj_weight', 'gmhra.7.attn.in_proj_bias', 'gmhra.7.attn.out_proj.weight', 'gmhra.7.attn.out_proj.bias', 'gmhra.7.ln_1.weight', 'gmhra.7.ln_1.bias', 'gmhra.7.mlp.c_fc.weight', 'gmhra.7.mlp.c_fc.bias', 'gmhra.7.mlp.c_proj.weight', 'gmhra.7.mlp.c_proj.bias', 'gmhra.7.ln_2.weight', 'gmhra.7.ln_2.bias', 'gmhra.7.ln_3.weight', 'gmhra.7.ln_3.bias'], unexpected_keys=['norm.weight', 'norm.bias', 'head.weight', 'head.bias', 'blocks.39.norm1.weight', 'blocks.39.norm1.bias', 'blocks.39.attn.q_bias', 'blocks.39.attn.v_bias', 'blocks.39.attn.qkv.weight', 'blocks.39.attn.proj.weight', 'blocks.39.attn.proj.bias', 'blocks.39.norm2.weight', 'blocks.39.norm2.bias', 'blocks.39.mlp.fc1.weight', 'blocks.39.mlp.fc1.bias', 'blocks.39.mlp.fc2.weight', 'blocks.39.mlp.fc2.bias'])
freeze vision encoder
open module: ['gmhra_cls_token', 'gmhra.0.dpe.weight', 'gmhra.0.dpe.bias', 'gmhra.0.attn.in_proj_weight', 'gmhra.0.attn.in_proj_bias', 'gmhra.0.attn.out_proj.weight', 'gmhra.0.attn.out_proj.bias', 'gmhra.0.ln_1.weight', 'gmhra.0.ln_1.bias', 'gmhra.0.mlp.c_fc.weight', 'gmhra.0.mlp.c_fc.bias', 'gmhra.0.mlp.c_proj.weight', 'gmhra.0.mlp.c_proj.bias', 'gmhra.0.ln_2.weight', 'gmhra.0.ln_2.bias', 'gmhra.0.ln_3.weight', 'gmhra.0.ln_3.bias', 'gmhra.1.dpe.weight', 'gmhra.1.dpe.bias', 'gmhra.1.attn.in_proj_weight', 'gmhra.1.attn.in_proj_bias', 'gmhra.1.attn.out_proj.weight', 'gmhra.1.attn.out_proj.bias', 'gmhra.1.ln_1.weight', 'gmhra.1.ln_1.bias', 'gmhra.1.mlp.c_fc.weight', 'gmhra.1.mlp.c_fc.bias', 'gmhra.1.mlp.c_proj.weight', 'gmhra.1.mlp.c_proj.bias', 'gmhra.1.ln_2.weight', 'gmhra.1.ln_2.bias', 'gmhra.1.ln_3.weight', 'gmhra.1.ln_3.bias', 'gmhra.2.dpe.weight', 'gmhra.2.dpe.bias', 'gmhra.2.attn.in_proj_weight', 'gmhra.2.attn.in_proj_bias', 'gmhra.2.attn.out_proj.weight', 'gmhra.2.attn.out_proj.bias', 'gmhra.2.ln_1.weight', 'gmhra.2.ln_1.bias', 'gmhra.2.mlp.c_fc.weight', 'gmhra.2.mlp.c_fc.bias', 'gmhra.2.mlp.c_proj.weight', 'gmhra.2.mlp.c_proj.bias', 'gmhra.2.ln_2.weight', 'gmhra.2.ln_2.bias', 'gmhra.2.ln_3.weight', 'gmhra.2.ln_3.bias', 'gmhra.3.dpe.weight', 'gmhra.3.dpe.bias', 'gmhra.3.attn.in_proj_weight', 'gmhra.3.attn.in_proj_bias', 'gmhra.3.attn.out_proj.weight', 'gmhra.3.attn.out_proj.bias', 'gmhra.3.ln_1.weight', 'gmhra.3.ln_1.bias', 'gmhra.3.mlp.c_fc.weight', 'gmhra.3.mlp.c_fc.bias', 'gmhra.3.mlp.c_proj.weight', 'gmhra.3.mlp.c_proj.bias', 'gmhra.3.ln_2.weight', 'gmhra.3.ln_2.bias', 'gmhra.3.ln_3.weight', 'gmhra.3.ln_3.bias', 'gmhra.4.dpe.weight', 'gmhra.4.dpe.bias', 'gmhra.4.attn.in_proj_weight', 'gmhra.4.attn.in_proj_bias', 'gmhra.4.attn.out_proj.weight', 'gmhra.4.attn.out_proj.bias', 'gmhra.4.ln_1.weight', 'gmhra.4.ln_1.bias', 'gmhra.4.mlp.c_fc.weight', 'gmhra.4.mlp.c_fc.bias', 'gmhra.4.mlp.c_proj.weight', 'gmhra.4.mlp.c_proj.bias', 'gmhra.4.ln_2.weight', 'gmhra.4.ln_2.bias', 'gmhra.4.ln_3.weight', 'gmhra.4.ln_3.bias', 'gmhra.5.dpe.weight', 'gmhra.5.dpe.bias', 'gmhra.5.attn.in_proj_weight', 'gmhra.5.attn.in_proj_bias', 'gmhra.5.attn.out_proj.weight', 'gmhra.5.attn.out_proj.bias', 'gmhra.5.ln_1.weight', 'gmhra.5.ln_1.bias', 'gmhra.5.mlp.c_fc.weight', 'gmhra.5.mlp.c_fc.bias', 'gmhra.5.mlp.c_proj.weight', 'gmhra.5.mlp.c_proj.bias', 'gmhra.5.ln_2.weight', 'gmhra.5.ln_2.bias', 'gmhra.5.ln_3.weight', 'gmhra.5.ln_3.bias', 'gmhra.6.dpe.weight', 'gmhra.6.dpe.bias', 'gmhra.6.attn.in_proj_weight', 'gmhra.6.attn.in_proj_bias', 'gmhra.6.attn.out_proj.weight', 'gmhra.6.attn.out_proj.bias', 'gmhra.6.ln_1.weight', 'gmhra.6.ln_1.bias', 'gmhra.6.mlp.c_fc.weight', 'gmhra.6.mlp.c_fc.bias', 'gmhra.6.mlp.c_proj.weight', 'gmhra.6.mlp.c_proj.bias', 'gmhra.6.ln_2.weight', 'gmhra.6.ln_2.bias', 'gmhra.6.ln_3.weight', 'gmhra.6.ln_3.bias', 'gmhra.7.dpe.weight', 'gmhra.7.dpe.bias', 'gmhra.7.attn.in_proj_weight', 'gmhra.7.attn.in_proj_bias', 'gmhra.7.attn.out_proj.weight', 'gmhra.7.attn.out_proj.bias', 'gmhra.7.ln_1.weight', 'gmhra.7.ln_1.bias', 'gmhra.7.mlp.c_fc.weight', 'gmhra.7.mlp.c_fc.bias', 'gmhra.7.mlp.c_proj.weight', 'gmhra.7.mlp.c_proj.bias', 'gmhra.7.ln_2.weight', 'gmhra.7.ln_2.bias', 'gmhra.7.ln_3.weight', 'gmhra.7.ln_3.bias']
open ln_vision
Loading VIT Done
Loading Q-Former
Drop_path:[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
BertConfig {
  "add_cross_attention": true,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.0,
  "classifier_dropout": null,
  "cross_attention_freq": 2,
  "drop_path_list": [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  "encoder_width": 1408,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.0,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "query_length": 32,
  "transformers_version": "4.28.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Load QFormer from model/blip2_pretrained_flant5xxl.pth
_IncompatibleKeys(missing_keys=['visual_encoder.cls_token', 'visual_encoder.pos_embed', 'visual_encoder.gmhra_cls_token',
Add extra 64 tokens in QFormer
freeze Qformer
Loading Q-Former Done
Loading LLAMA
Loading checkpoint shards: 100% 3/3 [00:08<00:00,  2.68s/it]
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at /content/drive/MyDrive/language_module/llama_folder/vicuna-7b-v0 and are newly initialized: ['model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.31.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq' ...
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
freeze LLAMA
Loading LLAMA Done
Load VideoChat from: /content/drive/MyDrive/language_module/videochat_weight/videochat_7b.pth
_IncompatibleKeys(missing_keys=['query_tokens', 'visual_encoder.cls_token', 'visual_encoder.pos_embed', 
Initialization Finished
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://5a6ee60098f9bc62b3.gradio.live/

**Comment by iambadbadboy** [comment]
GPU A100, high ram(85gb), gpu ram (40GB), no issue with that

**Comment by yinanhe** [comment]
We encountered a similar situation before due to incorrect conversion of LLM parameters. Please make sure you have downloaded the LLaMA checkpoints and the weights of vicuna-7b-delta-v0, and converted them without any errors.

**Comment by robotNo201** [comment]
Thank you so much, I will tryna test it again

**Comment by robotNo201** [comment]
> We encountered a similar situation before due to incorrect conversion of LLM parameters. Please make sure you have downloaded the LLaMA checkpoints and the weights of vicuna-7b-delta-v0, and converted them without any errors.

I got a question, for llama model, we can choose from the 3 below right? LLAMA, stable vicuna 13b or stable vicuna 7b, then after we preprocess the weight and get the output folder, we put the folder directory to the config.json, is that correct?

**Comment by yinanhe** [comment]
During the process of weight conversion, the original weights of llama-7b and llama-13b are required. Please note that it is llama1 here, not llama2. When obtaining vicuna-7b-v0, we also need the weights of vicuna-7b-delta-v0; when obtaining stable-vicuna-13b, we also need the weights of stable-vicuna-13b-delta. Then we only need to use the converted weights for filling in config.json, such as vicuna-7b-v0 or stable-vicuna-13b, instead of *delta or the original weights of llama.



At 2024-02-04 13:00:51, "robotNo201" ***@***.***> wrote:

We encountered a similar situation before due to incorrect conversion of LLM parameters. Please make sure you have downloaded the LLaMA checkpoints and the weights of vicuna-7b-delta-v0, and converted them without any errors.

I got a question, for llama model, we can choose from the 3 below right? LLAMA, stable vicuna 13b or stable vicuna 7b, then after we preprocess the weight and get the output folder, we put the folder directory to the config.json, is that correct?

**Comment by yinanhe** [comment]
BTW, a friendly reminder: We have launched [video chat2](https://github.com/OpenGVLab/Ask-Anything/tree/main/video_chat2), which outperforms video chat1.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
