### ISSUE TITLE
Getting <unk><unk><unk>......<unk> for output

### ISSUE THREAD

**Issue by Coronal-Halo** [OpenGVLab/Ask-Anything#125]
I downloaded all the weights/checkpoints and successfully converted corresponding Vicuna weights, and got the expected results on my computer with an RTX 4090. 

However, I have problem trying to replicate the results on a second computer (with Tesla V100 GPU). The model output is always ``` <UNK> <UNK> <UNK> ...... <UNK> ``` without any errors when I feed it with an input video. I followed the exact same weight conversion process without any error. 

Update: I tested on a third computer with an RTX 3080 ti and got the expected output as well, using the weights converted on the first computer. Only the computer with Tesla V100 gives me ``` <UNK> <UNK> <UNK> ...... <UNK> ```  as output, due to the ```hidden_states``` of the class ```LlamaModel``` with vicuna-7b-v0 weigths being ```[nan, nan, ..., nan]```. Whereas when I get the correct output, the output_token is a [1, 64] tensor of non-zero values. 

I tested the exact same code and weight files on all 3 machines with the exact same conda environment (and cuda = 11.7). I set low_resource == True since the none of the GPUs can fit the model by itself. I wonder what can possibly be the cause of this???

**Comment by Andy1621** [comment]
Hi! Could you try to use `bfloat16` to check the output? I'm not sure whether the `fp16` affects the output.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
