### ISSUE TITLE
Is there a bug in mvbench check_ans?

### ISSUE THREAD

**Issue by sunwhw** [OpenGVLab/Ask-Anything#126]
I noticed that sometimes the model would return an empty answer"". However, the empty answer is turned out to be correct by the "check_ans".
<img width="841" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/48038000/65412d26-d21d-4dce-9fcc-8ea510713b34">

**Comment by Andy1621** [comment]
Good question! Can you provide some cases to generate an empty answer? In my experiments, the model always generates options with the answer prompt.

**Comment by sunwhw** [comment]
oh, I am testing some unpublic model, it give empty response sometimes, I think it is the mvbench prompt doesn't fit the model, so it give such a strange response.

**Comment by Andy1621** [comment]
You can change the evaluation code to fit your model~

**Comment by sunwhw** [comment]
ok, Thanks!

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
