### ISSUE TITLE
Can you provide scripts for generating question & candidates using ChatGPT?

### ISSUE THREAD

**Issue by cmh1027** [OpenGVLab/Ask-Anything#128]
Fine-grained Pose (NTU RGBD), Scene Transition (MovieNet), Unexpected action (FunQA), Egocentric Navigation (VLN-CE)
Datasets of these tasks don't have QA annotations and it seems that you generate annotations by yourself with aid of ChatGPT.
Could you provide related scripts you used for this?

**Comment by Andy1621** [comment]
Good question!
1. Fine-grained Pose: We manually combine similar poses and randomly generate the candidates, like `drop(5), pick up(6), sit down(8), stand up(9), hopping(26), jump up(27), squat down(80)`.
2. Scene Transition: We generate the candidates based on the scene annotation, then use ChatGPT to generate the candidates like `Based on 'From the courtroom to the prison.', please create three similar sentences with different places`.
3. Unexpected action: We use similar prompts as in the original paper to generate the option as follows
```python3
"You are now an assistant for data augmentation. You have extensive experience in video understanding and have mastered this skill. I will provide you with a 'question' and 'answer' regarding a counter-intuitive video.\n" + \
"Your task is to help me understand the content of this paragraph and generate one English question-answer pair from it. The generated question should be closely related to the provided answer.\n" + \
"The format will be multiple choice, where each question has four options - one correct answer and three distractors.\n" + \
f'Question: "{question.strip()}"\n' + \
f'Answer: "{answer.strip()}"\n' + \
"To avoid cheating, the lengths of the correct answer and other distractors MUST be similar.\n" + \
"You need to ONLY return the generated QA in JSON like {'question': '', 'options': [], 'answer': ''}"
```
  We will check the option's length. If the length difference is large, we will regenerate it.

4. Egocentric Navigation: We randomly generate the candidates from `move forward, stop, turn left and move forward, turn right and move forward`.

**Comment by cmh1027** [comment]
I can't find question annotations, as well as options you mentioned. I navigated the datasets, but the question annotations were not in the original datasets. At least It seems that Fine-grained Pose has limited set of questions (like, Which one of these descriptions correctly matches the actions in the video?) but the others don't.

**Comment by Andy1621** [comment]
For the questions, we generate it by ChatGPT~

**Comment by cmh1027** [comment]
@Andy621 Could you provide the prompt for MovieNet and VLN-CE?

**Comment by Andy1621** [comment]
I don't save the specific prompt to generate the question. I remember that I used a similar prompt as I used to generate instruction data.
<img width="415" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/24236723/4eb626a8-a77c-4a05-afd3-e4ed218f0864">

**Comment by Andy1621** [comment]
I don't save the specific prompt... I remember that I required ChatGPT to generate some basic questions.

**Comment by cmh1027** [comment]
For example in scene_transition,
```
        "video": "Top006_08310.mp4",
        "question": "Which choice matches the scene changes in the video?",
        "candidates": [
            "From the kitchen to the dining room.",
            "From the staircase to the gangway.",
            "From the bedroom to the bathroom.",
            "From the classroom to the library."
        ],
        "answer": "From the staircase to the gangway."
```
I wonder where the answer "From the staircase to the gangway" came from.
There's no related data in the original MovieNet dataset

**Comment by cmh1027** [comment]
In addition, It seems that MovieNet currently does not provide video data due to copyright issue. Where did you get videos like Top006_08310.mp4?

**Comment by Andy1621** [comment]
Good question! It's a wrong cite when preparing the paper. We actually use the videos in [MoVQA](https://arxiv.org/abs/2312.04817), we will fix it later.

**Comment by cmh1027** [comment]
I see. It seems the dataset hasn't released yet. Is there any plan to release it? Or could you provide me with the dataset?

**Comment by Andy1621** [comment]
Since I'm not the authors, you can email the authors for more details.

**Comment by cmh1027** [comment]
In action sequence task of STAR dataset, the paper states that it directly adopts QA of original dataset. However, annotation is quite different from the original one. In the annotation of MVbench, more than half questions start with "What happened after ~?" Meanwhile, I can't find corresponding questions which start with such sentence in STAR dataset annotation. Can you clarify this discrepancy?

**Comment by Andy1621** [comment]
Please check those `Sequence` data in `STAR`. We do not use those QA contains `to the` which is about object.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
