### ISSUE TITLE
How are GPT4V/Gemini models evaluated?

### ISSUE THREAD

**Issue by Xarangi** [OpenGVLab/Ask-Anything#129]
I notice the paper (VideoChat2) points out that GPT4V uses 16 frames (which I assume are sampled uniformly). However, how is this input into the model given it accepts only single images at a time? Is there some sample prompt for this?

**Comment by yinanhe** [comment]
For fairness, we input all video models with a uniform sampling of 16 frames into the model. You can refer to the official cookbook for examples: [OpenAI Cookbook](https://cookbook.openai.com/examples/gpt_with_vision_for_video_understanding).

**Comment by Xarangi** [comment]
Thank you! That's really helpful
