### ISSUE TITLE
Difficulties running video_chat2

### ISSUE THREAD

**Issue by kavindie** [OpenGVLab/Ask-Anything#130]
Is there an issue with the setup instructions to run the `demo.py`?

I am following the instructions of [video_chat2/README.md](https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/README.md). I am stuck at "Stage3 training": Where do I download the files of `OpenGVLab/VideoChat2-IT`? The file structure and names do not line up with those referenced in error messages or the code.

This is an extremely lengthy process just to run the model. Can you please upload the pre-trained weights directly? For a stand-alone system, why not upload all the files required to run it (`umt_l16_qformer.pth`, `videochat2_7b_stage2.pth`, etc.) in one place, and without additional processing?

Secondly, is the online demo ([here](https://vchat.opengvlab.com/) or [here](https://huggingface.co/spaces/OpenGVLab/VideoChat2)) working properly? I am not able to upload a video successfully. Is it possible to run the demo using huggingface's "[run with docker](https://huggingface.co/docs/hub/spaces-run-with-docker)" ability?

I am mainly interested in using the model for downstream tasks. I appreciate any guidance you can give in making the demo work. I have been unsuccessfully trying to implement this for a while.
Thank you for any support.

**Comment by yinanhe** [comment]
Sorry for the late reply. 

[UMT-L-Qformer](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/umt_l16_qformer.pth)
[VideoChat2_7B_stage2](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/videochat2_7b_stage2.pth)
[VideoChat2_7B_stage3](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/videochat2_7b_stage3.pth)
[Vicuna-7B-delta](https://huggingface.co/lmsys/vicuna-7b-delta-v0)
**NOTE: This "delta model" cannot be used directly.**
Users have to apply it on top of the original LLaMA weights to get actual Vicuna weights. See [instructions](https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md#how-to-apply-delta-weights-for-weights-v11-and-v0).

**Comment by yinanhe** [comment]
As of now, [here](https://vchat.opengvlab.com/) and [here](https://huggingface.co/spaces/OpenGVLab/VideoChat2) are working fine.  We apologize for the inconvenience, but we are currently unable to support "run with docker" as our GPU-equipped machine is unable to run Docker.
