### ISSUE TITLE
the answer result seems to be simiplied

### ISSUE THREAD

**Issue by XuankeShi** [OpenGVLab/Ask-Anything#131]
It seems that the output results of the web demo have become simpler. I want to know what changes have taken place. There were many repeated answers before.

**Comment by yinanhe** [comment]
Web demo was updated from videochat to videochat2 in Nov 2023.

**Comment by XuankeShi** [comment]
I'll test it again. Maybe it's just because the test video is different.  Sometimes,  the answer is complicated and redundant

**Comment by yinanhe** [comment]
During the testing phase, certain videos may cause the video chat to experience repeated speech. If you encounter any issues, please feel free to provide feedback at any time :)

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
