### ISSUE TITLE
get_text_encoder is None in VideoChat2

### ISSUE THREAD

**Issue by idejie** [OpenGVLab/Ask-Anything#132]
https://github.com/OpenGVLab/Ask-Anything/blob/332b3ee84c1a5719cf69d26a487ab2f98f85cacb/video_chat2/tasks/retrieval_utils.py#L143

https://github.com/OpenGVLab/Ask-Anything/blob/332b3ee84c1a5719cf69d26a487ab2f98f85cacb/video_chat2/models/videochat2_qformer.py#L372

**Comment by Andy1621** [comment]
Thanks for your question! Since the code is modified from [UMT](https://github.com/OpenGVLab/unmasked_teacher), we forgot to remove this unused file.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
