### ISSUE TITLE
video chat2 dataset cc3m path

### ISSUE THREAD

**Issue by zhang-yunfan** [OpenGVLab/Ask-Anything#133]
Hi,
Thanks for sharing your code.

But may i check with you that 
FileNotFoundError: [Errno 2] No such file or directory: 'xxxxAsk-Anything/video_chat2/data/vindlu/videos_images/cc3m/a5756e3bb0da5bf21e4824585c12ebfb80e48356faf9cabce3f41b96a410ff9c.jpg'

for cc3m image, what is the meaning of the filename please? 
How shall i get access to this files please.

**Comment by yinanhe** [comment]
`xxxxAsk-Anything/video_chat2/data/vindlu/videos_images/cc3m/` is your root of cc3m, `a5756e3bb0da5bf21e4824585c12ebfb80e48356faf9cabce3f41b96a410ff9c.jpg` is the image of cc3m. You may download it from https://github.com/rom1504/img2dataset/blob/main/dataset_examples/cc3m.md

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
