### ISSUE TITLE
urgent problem

### ISSUE THREAD

**Issue by robotNo201** [OpenGVLab/Ask-Anything#135]
language_module/Ask-Anything-main/Ask-Anything-main/video_chat/models/eva_vit.py", line 248, in __init__
    num_patches = (img_size[1] // patch_size[1]) * (img_size[0] // patch_size[0])
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

First time it works, gradio works too, same code, after close the gradio and run the cell on colab again, it prints this error, but my comment is:

**DONT WASTE UR TIME ON THIS B*** S*****

By the way, even python version can make different result.

**Comment by Andy1621** [comment]
lol
