### ISSUE TITLE
 RuntimeError: checkpoint url or path is invalid

### ISSUE THREAD

**Issue by abdull6771** [OpenGVLab/Ask-Anything#137]
00             checkpoint = torch.load(model_path, map_location="cpu")
    101         else:
--> 102             raise RuntimeError("checkpoint url or path is invalid")
    103 
    104         state_dict = checkpoint["model"]

RuntimeError: checkpoint url or path is invalid

**Comment by Andy1621** [comment]
Could you provide the detailed file?
