### ISSUE TITLE
no info about kwai-videoLLM on the MVBench Leaderboard

### ISSUE THREAD

**Issue by cyj95** [OpenGVLab/Ask-Anything#138]
<img width="735" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/31176427/640e1067-89e3-4c6d-8376-425845a3860f">
what is this method？

**Comment by yinanhe** [comment]
Sorry, this model was uploaded by the user himself. The user did not provide relevant information or links, and we have no further information.
