### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by LHcver** [OpenGVLab/Ask-Anything#14]
在 video_chat_with_StableLM项目下运行 python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'会显示安装不了 请问是为什么

**Comment by yinanhe** [comment]
什么提示呢？

**Comment by LHcver** [comment]
> 什么提示呢？

我已经解决好了  谢谢您的及时解答
首先 你先下载到本地（ps：一定要把setup.py下载下来）
其次 上传到服务器指定路径中
最后在指定路径下 pip install . (注：该路径下一定要有setup.py文件）

**Comment by yinanhe** [comment]
感谢您的反馈~
