### ISSUE TITLE
34b large language model hermes2_yi34b

### ISSUE THREAD

**Issue by hn18001** [OpenGVLab/Ask-Anything#144]
Recently, som MLLMs hava adapted hermes2_yi34b  as base language model, such as [InternVL](hermes2_yi34b), [LLava](https://github.com/haotian-liu/LLaVA) . Have your team applied it to the project, like videochat2?

**Comment by Andy1621** [comment]
Great! We have applied Mistral and it works better. We can try to apply other models and release in next few weeks.

**Comment by hn18001** [comment]
Quick reply！ :thumbsup: 
How many GPU have you used to train Mistral？

**Comment by Andy1621** [comment]
For fast training, we use 32 A100 to first align Mistral with 25M data for 1 epoch, and the other 1M instruction data for 3 epochs.

**Comment by Andy1621** [comment]
For efficient training, I suggest using some other strategies as shown in [LAVIN](https://github.com/luogen1996/LaVIN).

**Comment by hn18001** [comment]
Got it! Looking forward your new work.
