### ISSUE TITLE
VideoChat2, 仅finetune stage3后，视频描述存在大量重复

### ISSUE THREAD

**Issue by ruishuzhao** [OpenGVLab/Ask-Anything#146]
作者好，
通过对videochat2中第三阶段的训练（训练集数据均来源于论文中提供的数据集），通过训练后模型对视频进行描述，会出现大量重复语句。
提问内容为："Describe the following video clip in detail."
回答如："The video clip shows a woman wearing a black shirt and black pants standing in a dark room. She is holding a white shirt and putting it into a washing machine. The woman is wearing a black shirt and black pants and is standing in a dark room. She is holding a white shirt and putting it into a washing machine. The woman is wearing a black shirt and black pants and is standing in a dark room. She is holding a white shirt and putting it into a washing machine. The woman is wearing a black shirt and black pants and is standing in a dark room. She is holding a white shirt and putting it into a washing machine. The woman is wearing a black shirt and black pants and is standing in a dark room. She is holding a white shirt and putting it into a washing machine. The woman is wearing a black shirt and black pants and is standing in a dark room. She is holding a white shirt and putting it into a washing machine. The woman is wearing a black shirt and black pants and is standing in a dark room. She is holding a white shirt and putting it into a"
其中反复出现“The woman is wearing a black shirt and black pants and is standing in a dark room. She is holding a white shirt and putting it into a washing machine. ”。

针对这种finetune后出现重复的问题，有比较好的解决方案吗？

辛苦帮忙解答一下。多谢~

**Comment by Andy1621** [comment]
这是一个不错的学术topic，因为在我们之前一些模型的推理上，也发现类似的问题，但具体是什么原因导致的不甚清楚。可以尝试修改不同的prompt，或者进行一些多轮对话提示，找一找原因或者解决方案

**Comment by ruishuzhao** [comment]
> 这是一个不错的学术topic，因为在我们之前一些模型的推理上，也发现类似的问题，但具体是什么原因导致的不甚清楚。可以尝试修改不同的prompt，或者进行一些多轮对话提示，找一找原因或者解决方案

再次感谢~

**Comment by yinanhe** [comment]
这种复读机问题在LLM中就存在，而且也有一些相应的[介绍和探索](https://zhuanlan.zhihu.com/p/666918508) 
对于VideoChat中，您可以尝试调整`answer`函数中的`num_beams`, `do_sample`, `top_p`, `repetition_penalty`, `temperature`. 其中调整 `repetition_penalty`可能效果会大一点，但是也会影响生成文本的随机性和多样性。您可以尝试`repetition_penalty`的取值范围调整到1以上进行探索一下~
https://github.com/OpenGVLab/Ask-Anything/blob/078540aaebfbe1ad9a109020a73b0ce173b355ef/video_chat2/conversation.py#L60-L75

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
