### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by LHcver** [OpenGVLab/Ask-Anything#15]
您好 
请问这俩个预训练模型该放在哪里tag2text_swin_14m.pth， grit_b_densecap_objectdet.pth

**Comment by yinanhe** [comment]
对应项目的`pretrained_models`下

**Comment by LHcver** [comment]
> pretrained_models
以您的video_chat_with_StableLM项目为例，
我找到了tag2text_swin_14m.pth这个存放的地方  放在model = tag2text_caption(pretrained="/opt/data/private/LH/Ask-Anything/video_chat_with_StableLM/tag2text_swin_14m.pth,", image_size=image_size, vit='swin_b' )这里 
可是我没有找到grit_b_densecap_objectdet.pth  应该加载在哪里
