### ISSUE TITLE
The final fine-tuned vision encoder

### ISSUE THREAD

**Issue by mojtaba-komeili** [OpenGVLab/Ask-Anything#154]
Your tables [here](https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/README.md#parrot-videochat2) explains very well how to fine-tune the model step by step. You also have some of the checkpoints along the way. But I cannot find the final checkpoint for the Vision model after the 3rd stage of fine-tuning. Wondering if that was missing from the list here?

**Comment by Andy1621** [comment]
Hi! The checkpoints in the table are finetuned after different stages.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
