### ISSUE TITLE
stage1无法eval

### ISSUE THREAD

**Issue by LanXingXuan** [OpenGVLab/Ask-Anything#156]
在训练stage1过程中，evaluate报错

models/videochat2_qformer.py  中的返回的是None
`    def get_text_encoder(self):
        return None`

导致tasks/retrieval_utils.py的143行中text_encoder = model.get_text_encoder()读不到，造成227-245行
`output = text_encoder(
    encoder_embeds=text_feats[topk_idx[j:]],
    attention_mask=text_atts[topk_idx[j:]],
    encoder_hidden_states=left_encoder_output,
    encoder_attention_mask=left_encoder_att,
    return_dict=True,
    mode="fusion",
)`
运行时报错，进而stage1训练过程中无法eval

请问应该怎么修改代码？

**Comment by riariam** [comment]
你好，我也遇到了同样的问题，请问您解决了吗

**Comment by JiamingHuHu** [comment]
大佬们好，请问你们解决这个问题了吗？
