### ISSUE TITLE
MVBench local evaluation

### ISSUE THREAD

**Issue by LiquidAmmonia** [OpenGVLab/Ask-Anything#158]
Hi great work and thank you for your contribution.

Is there any detailed instructions to download and process the original dataset in MVBench? e.g., 
- STAR [78]
- PAXION [75], 
- Moments in Time V1 [53], 
- FunQA [81], 
- CLEVRER [89], and so on.

**Comment by Andy1621** [comment]
You can simply download the data in [huggingface](https://huggingface.co/datasets/OpenGVLab/MVBench).

**Comment by LiquidAmmonia** [comment]
Thank you for your response, but it seems that the huggingface dataset does not contain the original video data?

**Comment by Andy1621** [comment]
Please check [here](https://huggingface.co/datasets/OpenGVLab/MVBench/tree/main/video).

**Comment by LiquidAmmonia** [comment]
got it. thank you for your patience~
