### ISSUE TITLE
After a few conversations, he was immediately sidetracked

### ISSUE THREAD

**Issue by kongbaiwubai** [OpenGVLab/Ask-Anything#17]
![1](https://user-images.githubusercontent.com/128248976/234501201-3f018c25-e47e-4d59-99dd-971a54688e01.png)
![2](https://user-images.githubusercontent.com/128248976/234501210-0d5c7f51-df3a-47ba-bd0b-ede505348705.png)
![3](https://user-images.githubusercontent.com/128248976/234501214-928a5d12-15dc-44e4-80b5-c089391827da.png)

**Comment by kongbaiwubai** [comment]
对他的回答进行追问，就会乱说

**Comment by yinanhe** [comment]
这个是我们的在线demo吗，离线部署可能不会遇到这个问题

**Comment by kongbaiwubai** [comment]
> 这个是我们的在线demo吗，离线部分可能不会遇到这个问题

是在线demo，我离线下在试试吧
