### ISSUE TITLE
Json files of pretraining dataset

### ISSUE THREAD

**Issue by qtli** [OpenGVLab/Ask-Anything#173]
I was following [DATA.md](https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/DATA.md) to download pretraining dataset.

However, I cannot find `webvid_10m_train.json`, `cc12m_train.json`, and so on from `OpenGVLab/VideoChat2-IT` repository. I was wondering how to download these annotation files to place under `anno_pretrain/` directory?

**Comment by bexxnaz** [comment]
You can download these datasets from the following links:

webvid-10M: [TempoFunk/webvid-10M](https://huggingface.co/datasets/TempoFunk/webvid-10M/tree/main)
cc12m: [GitHub Repository](https://github.com/rom1504/img2dataset/blob/main/dataset_examples/cc12m.md)

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
