### ISSUE TITLE
VideoChat2 Raw Training video download

### ISSUE THREAD

**Issue by mingzeG** [OpenGVLab/Ask-Anything#176]
Great Work! I was hoping to quickly get the raw video dataset used and try to train a videochat2, how could I get a filtered raw video dataset rather than downloading all the video datasets that the data.md mentioned. It's too memory consuming

**Comment by yinanhe** [comment]
Most of the videos are common and relatively easy to obtain. For some datasets that are more difficult to access, for EgoQA videos, download them from this [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/egoqa_split_videos.zip). For VideoChat2 conversation videos, download them from [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/videochat2_conversation_videos.zip). For Youcook, you can download it from [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/youcook_split_videos.zip)

**Comment by pengzhiliang** [comment]
Hello, @yinanhe, how to download the [CLEVRER](https://clevrer.csail.mit.edu/) dataset? The link shows noting.

**Comment by yinanhe** [comment]
@pengzhiliang  by [this link](https://dl.fbaipublicfiles.com/clevr/CLEVR_v1.0.zip)

**Comment by yinanhe** [comment]
@pengzhiliang  
You can download from the link below.
[Training Videos](http://data.csail.mit.edu/clevrer/videos/train/video_train.zip), [Annotations](http://data.csail.mit.edu/clevrer/annotations/train/annotation_train.zip), [Questions and Answers](http://data.csail.mit.edu/clevrer/questions/train.json)
[Validation Videos](http://data.csail.mit.edu/clevrer/videos/validation/video_validation.zip), [Annotations](http://data.csail.mit.edu/clevrer/annotations/validation/annotation_validation.zip), [Questions and Answers](http://data.csail.mit.edu/clevrer/questions/validation.json)
[Testing Videos](http://data.csail.mit.edu/clevrer/videos/test/video_test.zip), [Questions](http://data.csail.mit.edu/clevrer/questions/test.json)
[Object Masks and Attributes](http://data.csail.mit.edu/clevrer/derender_proposals.zip)
[Readme](http://data.csail.mit.edu/clevrer/README.txt)

**Comment by pengzhiliang** [comment]
@yinanhe Thanks vey much 🍻

**Comment by schopra8** [comment]
@yinanhe Do you have alternative links? The videos links aren't working for me.

**Comment by yinanhe** [comment]
@schopra8 We no longer have any other links. If you are still having difficulties in getting the data, please let me know which dataset it is.

**Comment by schopra8** [comment]
Apologies for the lack of specificity! I mean the [CLEVRER](https://clevrer.csail.mit.edu/) dataset specifically. The question+answers and README load for me -- but the videos don't, when I click on those links. 

I reached out to the original authors of the CLEVRER dataset as well, but they haven't responded.

**Comment by schopra8** [comment]
@yinanhe -- I'm also struggling to find the VideoChat videos used in the conversation and caption annotations. Do you have any pointers to where I can download this data? Thank you in advance!

**Comment by yinanhe** [comment]
> Apologies for the lack of specificity! I mean the [CLEVRER](https://clevrer.csail.mit.edu/) dataset specifically. The question+answers and README load for me -- but the videos don't, when I click on those links.
> 
> I reached out to the original authors of the CLEVRER dataset as well, but they haven't responded.

@schopra8  how about use link in  https://github.com/OpenGVLab/Ask-Anything/issues/176#issuecomment-2121805009. In my network environment, the download is normal.

**Comment by yinanhe** [comment]
> @yinanhe -- I'm also struggling to find the VideoChat videos used in the conversation and caption annotations. Do you have any pointers to where I can download this data? Thank you in advance!

The videos used here are from YouTube, and some videos might be found in the InternVid dataset on opendatlab.com.

**Comment by schopra8** [comment]
Thank you @yinanhe! 

- For [CLEVRER](https://clevrer.csail.mit.edu/) it looks like my browser was automatically trying to turn the HTTP link into HTTPS and that was why the file was not downloading. This works for me now.

- For the [VideoChat portion of the VidChat2 Instruction Tuning data](https://huggingface.co/datasets/OpenGVLab/VideoChat2-IT/viewer/video_caption/videochat) I see file names like "000551_000600/1054295129.mp4" but when I look at the [InternVid-10M dataset in HuggingFace](https://huggingface.co/datasets/OpenGVLab/InternVid?row=0) I only see YouTube Ids (e.g. "HdYoyzCSWyw"). How does one align the YouTube IDs to the names in the VidChat2 Instruction Tuning  dataset?

**Comment by schopra8** [comment]
I now see that the VideoChat data names correspond to WebVid like VideoChat2 -- and can resolve the videos.

@yinanhe - Thanks for all the help! It might be helpful to update the `Data.md` file to clarify that [VideoChat](**https://github.com/OpenGVLab/InternVideo/tree/main/Data/instruction_data**) corresponds to videos from WebVid. The link to `InternVid` threw me off -- and had me incorrectly looking at the [InternVid-10M Dataset ](https://huggingface.co/datasets/OpenGVLab/InternVid/viewer/InternVid-10M/FLT).

**Comment by xiaoqian-shen** [comment]
> Most of the videos are common and relatively easy to obtain. For some datasets that are more difficult to access, for EgoQA videos, download them from this [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/egoqa_split_videos.zip). For VideoChat2 conversation videos, download them from [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/videochat2_conversation_videos.zip). For Youcook, you can download it from [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/youcook_split_videos.zip)

Hi, the links seems not work. Could you check whether the bucket exists or not?

**Comment by yinanhe** [comment]
Now you can get the latest download link according to the issue [#223 ](https://github.com/OpenGVLab/Ask-Anything/issues/223)
> 
> [egoqa](https://huggingface.co/datasets/ynhe/videochat2_data/resolve/main/egoqa_split_videos.zip) [conversation](https://huggingface.co/datasets/ynhe/videochat2_data/resolve/main/videochat2_conversation_videos.zip) [youcook_split_videos_parta](https://huggingface.co/datasets/ynhe/videochat2_data/resolve/main/youcook_split_videos.zip.partaa) [youcook_split_videos_partb](https://huggingface.co/datasets/ynhe/videochat2_data/resolve/main/youcook_split_videos.zip.partab)
