### ISSUE TITLE
Qustion About Public Datasets Utilized by MvBench

### ISSUE THREAD

**Issue by GenuineWWD** [OpenGVLab/Ask-Anything#178]
Hi,
You mention in your paper  that your MvBench takes use of some public datasets, such as NTU RGB-D and so on. Do you use both train sets and test sets of these public datasets, or only the test sets to build MvBench?
Thanks!

**Comment by Andy1621** [comment]
For MVBench, we only use the test or val set.

**Comment by GenuineWWD** [comment]
Thank you for your explanation!
