### ISSUE TITLE
mistral版本三阶段训练代码问题

### ISSUE THREAD

**Issue by zhanghang-official** [OpenGVLab/Ask-Anything#179]
https://github.com/OpenGVLab/Ask-Anything/blob/cd1f925cff55a0a0dfa730bdac132035a900b140/video_chat2/dataset/it_dataset_mistral.py#L161
在调用load_and_transform_media_data_video函数时传入dynamic_config参数
https://github.com/OpenGVLab/Ask-Anything/blob/cd1f925cff55a0a0dfa730bdac132035a900b140/video_chat2/dataset/base_dataset.py#L69
但是load_and_transform_media_data_video函数定义并没有dynamic_config参数，会导致报错，请问dynamic_config参数什么作用，是否可以直接去掉dynamic_config。

**Comment by Andy1621** [comment]
可以的，我更正一下代码

**Comment by Andy1621** [comment]
代码更新过啦，这个参数是用来支持后续微调的，后面会更新一下~

**Comment by zhanghang-official** [comment]
好的 感谢！

**Comment by dragen1860** [comment]
> 代码更新过啦，这个参数是用来支持后续微调的，后面会更新一下~

没有更新啊，最新的代码：
commit 9648e8f14f19bd68ae7ad430a563a8550bcfb2bf (HEAD -> main, origin/main, origin/HEAD)
Author: Kunchang Li <812487273@qq.com>
Date:   Tue May 28 23:06:46 2024 +0800

    Update README.md

**Comment by Andy1621** [comment]
@zhanghang-official Hi! 我更新了大分辨率微调的代码，可以试用一下
