### ISSUE TITLE
New datasets used for videochat2_mistral

### ISSUE THREAD

**Issue by LiJiaqi96** [OpenGVLab/Ask-Anything#181]
Very happy to hear that you have updated the model with mistral LLM. Is there any place to find the newly added datasets? Thanks!

**Comment by Andy1621** [comment]
Good question! In the current version, only the `smit` is added. And we have updated the instruction data [here](https://huggingface.co/datasets/OpenGVLab/VideoChat2-IT/tree/main/video/caption/S-MiT).

**Comment by LiJiaqi96** [comment]
Thanks for your reply! I noticed that some datasets like image caption -- coco has been reduced to a smaller size (100k). I'm curious about the reason and whether it is because the length of captions are relatively short? Thanks

**Comment by LiJiaqi96** [comment]
OK, it's great to train faster with the same performance :)
