### ISSUE TITLE
how to implement batch_chat for videochat2 benchmark?

### ISSUE THREAD

**Issue by dragen1860** [OpenGVLab/Ask-Anything#187]
Dear author:
  Thnaks for the really solid work of videochat2.
  Recently i finetunning a individual model on my custom dataset and want to test on my benchmark samples, which as up to 30K samples.  It is extreme time-consuming for chat one by one and then compute the accuracy. Does anyone know how to implement a `batch_chat` like sytle parallel inference function, so that i could inference several samples meanwhile. thanks.

**Comment by Andy1621** [comment]
Hi! We will release the vllm verision for `batch_chat` recently.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
