### ISSUE TITLE
More large LLM potentials needed for the community!

### ISSUE THREAD

**Issue by dragen1860** [OpenGVLab/Ask-Anything#188]
Dear authors:
  It's very promising to witness that the stronger Mistral-7b llm models enhance the capability of video understanding. We would eager to see more potentials performed by replacing the llm with more strong models such as llama3, Yi-34b, InternLM. Specificlly,  please try to evaluate some llm models such as 34b, 70b and let the community know whether it helps.  Thank for such a great project.

**Comment by Andy1621** [comment]
Good idea! But current codebase is not friendly for larger LLM. We have updated VideoChat2-HD, which use large resolution for better results.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
