### ISSUE TITLE
can I simply set vit_l14 to larger input image size, such as 336/448, without re-training for stage2/3, videochat2?

### ISSUE THREAD

**Issue by dragen1860** [OpenGVLab/Ask-Anything#189]
hi, i want to test whether larger input image size helps my custom finetunning model performance. Does anyone know can i simply feed larger input image size without re-training on stage2&3. thank you.

**Comment by Andy1621** [comment]
Yes, you can~ Please follow the code:
<img width="994" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/24236723/3198b41d-7921-4792-abd5-748d1af71d52">

**Comment by dragen1860** [comment]
ok, I will try.
