### ISSUE TITLE
More GPU memory for new mistrail version..

### ISSUE THREAD

**Issue by yuanrr** [OpenGVLab/Ask-Anything#192]
When I finetuned videochat2-mistral on 4090, I found that the mistral version was always out of memory. It was probably due to the use of lora for more layers (originally just q and v).

Could you please give me some suggestions about how to finetune the new version in about 24g GPU memory....thanks a lot : )

**Comment by Andy1621** [comment]
Can you try to freeze the lora and LLM? If it's okay, I think you can load the original LoRA, and only update part of them.

**Comment by Andy1621** [comment]
Thanks for your good try! I have not tried to adopt 8-bit training seriously, since it leads to unstable training when I tried a few months ago and then stop the exploration.

**Comment by yuanrr** [comment]
Thank you for your kind reply : )
