### ISSUE TITLE
The evaluation for EgoSchema

### ISSUE THREAD

**Issue by 921112343** [OpenGVLab/Ask-Anything#195]
Thank you for open-sourcing this excellent work. I have noticed that your model performs exceptionally well on the EgoSchema dataset. However, I found detailed descriptions of your evaluation process only for NExT-QA, STAR, and TVQA in the Readme. Could you please share the steps you took to prepare the EgoSchema data and how you evaluated your model on it?

**Comment by Andy1621** [comment]
@921112343 Please check https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/demo/demo_mistral.ipynb

**Comment by yuanrr** [comment]
Very wonderful update !! Could you please also offer some examples for evaluating zero-shot videoqa, like msvd and msrvtt....thanks a lot !

**Comment by Andy1621** [comment]
For the VideoQA, you can simply modify the code and save the responses, and then use ChatGPT to give a score.

However, I don't suggest to evaluate the VideoLMMs' capacities on the tradictional QA benchmarks like MSRVTT/MSVD, which can not reveal their essential problems.

**Comment by yuanrr** [comment]
Thank you for your reply, I was wondering if any new work has been done recently to discuss this metric like MSRVTT/MSVD....cause your view is very new to me...

**Comment by 921112343** [comment]
> @921112343 Please check https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/demo/demo_mistral.ipynb

Thanks for your update!!

**Comment by Andy1621** [comment]
> Thank you for your reply, I was wondering if any new work has been done recently to discuss this metric like MSRVTT/MSVD....cause your view is very new to me...

No work discuss the potential bias in such benchmark, but one paper has reveled the `single frame bias` about the video dataset. Please check `Revealing Single Frame Bias for Video-and-Language Learning`.
