### ISSUE TITLE
question about vision encoder

### ISSUE THREAD

**Issue by Nastu-Ho** [OpenGVLab/Ask-Anything#196]
<img width="1049" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/39642013/5f3a3046-ce49-4c7c-a1a2-f1c5bea9902c">
Is the vision encoder used here umt-l or internvideo2-1B?
I saw that the mistral version in internvideo2 had similar results to the one here

**Comment by Andy1621** [comment]
Hi! We released UMT-L since it runs faster.

**Comment by yepzhang** [comment]
> Hi! We released UMT-L since it runs faster.
hi! will you release internvideo2 version in the future?

**Comment by yepzhang** [comment]
> Hi! We released UMT-L since it runs faster.

Hello! Will you release internvideo2 version in there future? thanks~

**Comment by yinanhe** [comment]
> > Hi! We released UMT-L since it runs faster.
> 
> Hello! Will you release internvideo2 version in there future? thanks~

@yepzhang  Sure, You can found the internvideo2-chat in [huggingface](https://huggingface.co/collections/OpenGVLab/internvideo2-6618ccb574bd2f91410df5cd)
