### ISSUE TITLE
Suggestion about MVBench

### ISSUE THREAD

**Issue by LiJiaqi96** [OpenGVLab/Ask-Anything#197]
Hi, I notice that multiple submissions of the same group to MVBench would result in multiple (rather than one) records on the leaderboard. Is it possible to make some updates for this issue, in order that the rank on the leaderboard can be more reasonable? Maybe the leaderboard display the best result of the same model name could be a good choice:)

**Comment by yinanhe** [comment]
Thanks for raising a very good question, we actually reserve the `revision model name` block in the submission page, if the user want to update the number in the origin list, he/she can consider filling this field. We will also clean the repeated data regularly.

**Comment by LiJiaqi96** [comment]
Thanks for your efforts!
