### ISSUE TITLE
No star/Charades_v1_480/EDXBD.mp4 in the new MVBench (AS)

### ISSUE THREAD

**Issue by LiquidAmmonia** [OpenGVLab/Ask-Anything#198]
In the newly updated json file of Action Sequence (MVBench) there is a video of star/Charades_v1_480/EDXBD.mp4, which seems to be missing in the provided video archive.

**Comment by Andy1621** [comment]
Thanks for your feedback. We will update the videos soon. By the way, you can use the original version, since there is a marginal difference.

**Comment by Andy1621** [comment]
Please check [here](https://huggingface.co/datasets/OpenGVLab/MVBench/blob/main/video/data0613.zip).
