### ISSUE TITLE
Video source of the updated VideoChat2-it-HD

### ISSUE THREAD

**Issue by LiquidAmmonia** [OpenGVLab/Ask-Anything#203]
Hi, great work and thank you for your contribution in the open-source community. The recently updated instruction dataset seems to be only contain the annotation of the newly added data. Will there be guides to the video files as the previous released in the DATA.md file?

**Comment by Andy1621** [comment]
Hi~ The data can be directly downloaded from their official repos. For example, https://github.com/OpenGVLab/Ask-Anything/issues/194#issuecomment-2191050559

**Comment by LiquidAmmonia** [comment]
Thank you for your reply.
