### ISSUE TITLE
How to get dataset?

### ISSUE THREAD

**Issue by caichaoxiang** [OpenGVLab/Ask-Anything#205]
Hello, I would like to ask if videochat2-it has any officially provided processed data, including the storage format of the data, because I found that some data links on your huggingface (https://huggingface.co/datasets/OpenGVLab/VideoChat2-IT) have expired, and I don’t know how to process and store some data.

**Comment by yinanhe** [comment]
Some processed data that cannot find download links be found [here](https://github.com/OpenGVLab/Ask-Anything/issues/86).

**Comment by aabbc-cell** [comment]
I can't open this download link, it says AccessDenied

**Comment by yinanhe** [comment]
> I can't open this download link, it says AccessDenied

@aabbc-cell You can find it at https://huggingface.co/datasets/ynhe/videochat2_data/tree/main

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
