### ISSUE TITLE
Re. pretraining annotation files

### ISSUE THREAD

**Issue by pritamqu** [OpenGVLab/Ask-Anything#208]
Hey - thanks for your awesome work. Could you please point to the pretraining annotation files?

https://github.com/OpenGVLab/Ask-Anything/blob/0a79339cd4454f0584db0bca79d61737acc8166b/video_chat2/configs/data.py#L9

**Comment by Andy1621** [comment]
Hi! You can find these annotations [here](https://github.com/OpenGVLab/unmasked_teacher/blob/main/multi_modality/DATASET.md).

**Comment by pritamqu** [comment]
awesome!
