### ISSUE TITLE
VideoChat2-text basline 

### ISSUE THREAD

**Issue by BennoKrojer** [OpenGVLab/Ask-Anything#210]
Hello,

Thank you for putting out this amazing set of models, datasets and evals!
Is it possible to release the code and details for the VideoChat2-text baseline from your paper? I am studying some properties of video understanding and benchmarks and this baseline might be important!

Best,
Benno

**Comment by Andy1621** [comment]
Good question! In my experiments, I just input the `zero image` for `VideoChat2-text`. For example, changing the code in the `demo.ipynb`
```python3
img_list.append(image_emb) # original image
img_list.append(torch.zeros_like(image_emb)) # zero image
```

**Comment by BennoKrojer** [comment]
Thank you! I will try that out

**Comment by BennoKrojer** [comment]
@Andy1621 In the paper you say: "“VideoChat2text” denotes the model receiving blank videos and excludes
LoRA tuning, relying solely on the LLM’s capacity for responses".
Does that mean you ran the stage 2 model and not stage 3? Do you have any more details on whether the rest was the same such as prompting?

**Comment by BennoKrojer** [comment]
I ran both Stage 2 and Stage 3 models in our pipeline, but with zero-out video input, but the results look quite different to the paper unfortunately. We were able to reproduce the normal however up to 1-2% margin.

We would be very grateful if you can share any more details!

**Comment by Andy1621** [comment]
> @Andy1621 In the paper you say: "“VideoChat2text” denotes the model receiving blank videos and excludes LoRA tuning, relying solely on the LLM’s capacity for responses". Does that mean you ran the stage 2 model and not stage 3? Do you have any more details on whether the rest was the same such as prompting?

Hi! Actually, we run Stage3 model, which is training without LoRA for a fair comparison. 

<img width="432" alt="image" src="https://github.com/user-attachments/assets/ffce8603-c60b-4f36-8650-70ee4edcbd3c">

**Comment by BennoKrojer** [comment]
Interesting, thank you! Do you still have the weights somewhere for this?

**Comment by Andy1621** [comment]
Please try this [model](https://huggingface.co/Andy1621/VideoChat2_VicunaV0_7B_stage3_noLoRA/blob/main/videochat2_vicunav0_7b_stage3_noLoRA.pth) without LoRA. I just found it from the previous model weights and haven't tested it~

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
