### ISSUE TITLE
HD训练问题

### ISSUE THREAD

**Issue by zhanghang-official** [OpenGVLab/Ask-Anything#211]
HD的优化点在图像数据处理上，具体在训练时是直接在二阶段训练的模型上训练HD模型，还是先使用非HD配置训练三阶段模型，再使用相同数据用HD配置训练四阶段HD模型。

**Comment by Andy1621** [comment]
我们是在三阶段的模型上继续训练，使用了HD处理，以及不同的训练数据（分辨率更多，描述更精细）
