### ISSUE TITLE
Get an import error when install vllm by source 

### ISSUE THREAD

**Issue by Rhealalalala** [OpenGVLab/Ask-Anything#214]
When I import vllm after installing vllm by source, I get this error below. 
"ImportError: /opt/conda/lib/python3.10/site-packages/vllm/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi"
Could I get any tips?

**Comment by yinanhe** [comment]
It seems that you reinstalled another version of torch after installing vllm

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
