### ISSUE TITLE
VideoChat2_it_hd_mistral(config=cfg.model) 'bert base uncased' Error

### ISSUE THREAD

**Issue by daisyyywang** [OpenGVLab/Ask-Anything#216]
Hi I'm trying to follow this [demo](https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/demo/demo_mistral_hd.ipynb) for testing, and encountered an issue related to Bert Tokenizer , below is the the error message, can you help me to fix it ? thanks ! 
![Screenshot 2024-08-06 at 19 56 06](https://github.com/user-attachments/assets/9b38f7be-c63c-4f6e-93fe-ebdb6c6b19af)

**Comment by Andy1621** [comment]
Hi! Please set `local_files_only=False` if you do not download the weights.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
