### ISSUE TITLE
Unable to download pre-trained weights for VideoChat2

### ISSUE THREAD

**Issue by Lookuz** [OpenGVLab/Ask-Anything#219]
Hi, I am unable to access and download the weights for `umt_l16_qformer.pth`, `videochat2_7b_stage2.pth` and `videochat2_7b_stage3.pth` from `https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/`. I get a HTML page with an error message shown in the attached screenshot. Could you re-release the weights for download, or would there be any other way I can access the pre-trained weights on the site? Thanks!
<img width="748" alt="Screenshot 2024-08-12 at 3 35 52 PM" src="https://github.com/user-attachments/assets/8ed3fa7f-5496-4e83-b602-b6ebc47ce271">

**Comment by yinanhe** [comment]
https://huggingface.co/OpenGVLab/videochat/resolve/main/videochat2_7b_stage3.pth

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
