### ISSUE TITLE
Why "long video support" is need, and what’s new comparing to the main branch?

### ISSUE THREAD

**Issue by cocoshe** [OpenGVLab/Ask-Anything#22]
Thanks for your great work~
I noticed "A new branch for Watch videos longer than one minute with chatGPT."
So this means the main branch doesn't support video chat for longer than one minute, what's the reasons? And what's new comparing to the main branch?

**Comment by yinanhe** [comment]
In the main branch, videos can be input with any length, but when the video information longer than 1 minute is converted into text tokens and input into chatGPT, it will exceed the 4096 token limit of GPT-3.5. So in the "long video support" branch, we use some APIs of `langchain` to help us reduce tokens, so we can also introduce `whisper` to obtain subtitles for long videos, helping LLM to better understand videos.

**Comment by cocoshe** [comment]
> 
I got it. Thanks for your reply. 
BTW, if the max time length of video is approximately tested with the default frame sample rate?

**Comment by yinanhe** [comment]
The length of the video is indeed related to its frame sample rate. In the default experiment, we used 1fps. We did not test the actual maximum length in such detail, because the length of the text described in different videos is ever-changing

**Comment by cocoshe** [comment]
> The length of the video is indeed related to its frame sample rate. In the default experiment, we used 1fps. We did not test the actual maximum length in such detail, because the length of the text described in different videos is ever-changing. 1 minute is a relatively stable value we found in our tests, but not the most accurate.

OK, thanks~
