### ISSUE TITLE
Missing model

### ISSUE THREAD

**Issue by Hyu-Zhang** [OpenGVLab/Ask-Anything#220]
<img width="562" alt="image" src="https://github.com/user-attachments/assets/30e34684-e098-4dae-80b4-e652bc711c60">
Can you provide a link to download the model? The original link seems to be dead.

**Comment by yinanhe** [comment]
https://huggingface.co/OpenGVLab/videochat/resolve/main/umt_l16_qformer.pth

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
