### ISSUE TITLE
Question ; Why VideoChat2 divided into 3 stages for training? 

### ISSUE THREAD

**Issue by easyminnn** [OpenGVLab/Ask-Anything#221]
Hi, I am an undergraduate student, studying this repository. I have several questions.

It is noted that stage 1 needs 8 GPUs, and stage2 needs 4 GPUs.
But It seems that stage2 has more extended architecture(added LLM). 
Why does stage 1 need more GPUs than stage 2? 

And I also want to know that only stage 3 uses LoRA. 

Lastly, I also want to know why VideoChat2 divided into 3 stages for training? 

Thank you!!

**Comment by Andy1621** [comment]
For stage1, we follow BLIP-2 to train QFormer to compress token.
For stage2, we conduct simple tasks as in other VLLMs, which can be seen as `pretraining`.
For stage3, we collect diverse data for SFT.

**Comment by yinanhe** [comment]
Hi, we will close this issue.

Feel free to contact us if you have other questions.
