### ISSUE TITLE
 No module named 'models.videochat2_it'

### ISSUE THREAD

**Issue by seymaakorkmaz** [OpenGVLab/Ask-Anything#222]
(videochat2) root@58df28cdb848:/tf/Ask-Anything/video_chat2# python demo/demo.py
Traceback (most recent call last):
  File "/tf/Ask-Anything/video_chat2/demo/demo.py", line 17, in <module>
    from models.videochat2_it import VideoChat2_it
ModuleNotFoundError: No module named 'models.videochat2_it'

**Comment by Graysonicc** [comment]
have you resolved it ?

**Comment by seymaakorkmaz** [comment]
> have you resolved it ?

No

**Comment by yinanhe** [comment]
@seymaakorkmaz @Graysonicc  Hi. Sorry for the late reply. We have changed the organization form of the code, you can refer to https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/demo/demo_mistral_hd.ipynb .


In `demo/demo.py` you should change `from models.videochat2_it import VideoChat2_it` to `from model import VideoChat2_it_vicuna`

**Comment by seymaakorkmaz** [comment]
After changing the relevant part, I get this error:
(videochat2) root@58df28cdb848:/tf/Ask-Anything/video_chat2# python demo/demo.py
/root/anaconda3/envs/videochat2/lib/python3.9/site-packages/gradio/layouts/column.py:53: UserWarning: 'scale' value should be an integer. Usssues.
  warnings.warn(
Traceback (most recent call last):
  File "/tf/Ask-Anything/video_chat2/demo/demo.py", line 157, in <module>
    up_video = gr.Video(interactive=True, include_audio=True, elem_id="video_upload").style(height=360)
AttributeError: 'Video' object has no attribute 'style'

**Comment by Graysonicc** [comment]
demo.ipynb is OK. When i ran demo.py，i met the same problem—video no style

**Comment by Qnancy** [comment]
you can add these two lines:
import sys
sys.path.append('../Ask-Anything/video_chat2')[your path]

**Comment by yinanhe** [comment]
> demo.ipynb is OK. When i ran demo.py，i met the same problem—video no style

@Graysonicc This could be due to a version issue with gradio where you need to downgrade your version of gradio or remove style-related code from demo.py
