### ISSUE TITLE
source video links not available

### ISSUE THREAD

**Issue by xiaoqian-shen** [OpenGVLab/Ask-Anything#223]
> Most of the videos are common and relatively easy to obtain. For some datasets that are more difficult to access, for EgoQA videos, download them from this [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/egoqa_split_videos.zip). For VideoChat2 conversation videos, download them from [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/videochat2_conversation_videos.zip). For Youcook, you can download it from [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/youcook_split_videos.zip)

Hi, the links seems not work. Could you check whether the bucket exists or not?

_Originally posted by @xiaoqian-shen in https://github.com/OpenGVLab/Ask-Anything/issues/176#issuecomment-2297096030_

**Comment by yinanhe** [comment]
Thanks for pointing it out., you can get the latest download link according to the top issue. https://github.com/OpenGVLab/Ask-Anything/issues/86#issuecomment-1907273128

**Comment by xiaoqian-shen** [comment]
Thanks for reply! But it seems that the link of [Youcook](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/youcook_split_videos.zip) is still not working

**Comment by yinanhe** [comment]
The file of Youcook is relatively large and is still being uploaded. You can also consider obtaining it directly from the original dataset of Youcook.

**Comment by yinanhe** [comment]
@xiaoqian-shen  Hi, sorry for the late reply, youcook is now available.
See [youcook_split_videos_parta](https://huggingface.co/datasets/ynhe/videochat2_data/resolve/main/youcook_split_videos.zip.partaa)  and [youcook_split_videos_partb](https://huggingface.co/datasets/ynhe/videochat2_data/resolve/main/youcook_split_videos.zip.partab)

**Comment by xiaoqian-shen** [comment]
Thank you very much! This issue could conclude then.
