### ISSUE TITLE
no module name datasets

### ISSUE THREAD

**Issue by Graysonicc** [OpenGVLab/Ask-Anything#225]
![image](https://github.com/user-attachments/assets/9b9eaddf-3465-42e2-acd9-c3ae41af4cde)

**Comment by Graysonicc** [comment]
When i ran /Ask-Anything-main/video_chat2/tasks/train_qformer.py on remote servers, it said ModuleNotFoundError: No module named 'dataset'. However, there is no error or warning in the code and the code path is correct.

**Comment by yinanhe** [comment]
Please ensure that the path you are running is under the video_chat2 folder.
If not, you need to add `/root/Ask-Anything-main/video_chat2/` to your PYTHONPATH. You can execute `export PYTHONPATH=/root/Ask-Anything-main/video_chat2/:$PYTHONPATH` in the command line before running.

In addition, it is recommended that you refer to https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/scripts/videochat_vicuna/run_7b_stage1.sh to train the qformer. If you are not using slurm, you can refer to the following:

```
NNODE=4
OUTPUT_DIR="$(dirname $0)/$JOB_NAME"
torchrun --rdzv_endpoint=${MASTER_NODE}:${MASTER_PORT} --nnodes=${NNODE} \
    --nproc_per_node=${NUM_GPUS} \
    --rdzv_backend=c10d \
    tasks/train_qformer.py \
    $(dirname $0)/config_7b_stage1.py \
    output_dir ${OUTPUT_DIR}
```

**Comment by zhou186** [comment]
> 当我在远程服务器上运行 /Ask-Anything-main/video_chat2/tasks/train_qformer.py 时，它说 ModuleNotFoundError： No module named 'dataset'。但是，代码中没有错误或警告，并且代码路径是正确的。

请问解决了吗

**Comment by yinanhe** [comment]
> > 当我在远程服务器上运行 /Ask-Anything-main/video_chat2/tasks/train_qformer.py 时，它说 ModuleNotFoundError： No module named 'dataset'。但是，代码中没有错误或警告，并且代码路径是正确的。
> 
> 请问解决了吗

您遇到类似的问题了吗？我想上面的回答应该可以解决这个问题https://github.com/OpenGVLab/Ask-Anything/issues/225#issuecomment-2302083025

**Comment by zhou186** [comment]
> > > 当我在远程服务器上运行 /Ask-Anything-main/video_chat2/tasks/train_qformer.py 时，它说 ModuleNotFoundError： No module named 'dataset'。但是，代码中没有错误或警告，并且代码路径是正确的。
> > 
> > 
> > 请问解决了吗
> 
> 您遇到类似的问题了吗？我想上面的回答应该可以解决这个问题[#225 （comment）](https://github.com/OpenGVLab/Ask-Anything/issues/225#issuecomment-2302083025)
您好，正在运行的路径确实位于video_chat2文件夹下，我在远程服务器上运行的demo.py文件，报错ModuleNotFoundError: No module named 'dataset'。翻了翻文件夹，确实没有找到dataset
![1](https://github.com/user-attachments/assets/00c0ebcb-d985-4ea2-94c8-d1ed0cb646bc)

**Comment by yinanhe** [comment]
> > > > 当我在远程服务器上运行 /Ask-Anything-main/video_chat2/tasks/train_qformer.py 时，它说 ModuleNotFoundError： No module named 'dataset'。但是，代码中没有错误或警告，并且代码路径是正确的。
> > > 
> > > 
> > > 请问解决了吗
> > 
> > 
> > 您遇到类似的问题了吗？我想上面的回答应该可以解决这个问题[#225 （comment）](https://github.com/OpenGVLab/Ask-Anything/issues/225#issuecomment-2302083025)
> > 您好，正在运行的路径确实位于video_chat2文件夹下，我在远程服务器上运行的demo.py文件，报错ModuleNotFoundError: No module named 'dataset'。翻了翻文件夹，确实没有找到dataset
> > ![1](https://private-user-images.githubusercontent.com/137672318/360319769-00c0ebcb-d985-4ea2-94c8-d1ed0cb646bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTAxOTYsIm5iZiI6MTcyNDMwOTg5NiwicGF0aCI6Ii8xMzc2NzIzMTgvMzYwMzE5NzY5LTAwYzBlYmNiLWQ5ODUtNGVhMi05NGM4LWQxZWQwY2I2NDZiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNjU4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2VmZGJkYWYzM2JmZDBmZThhYjM0YzVlYWYwNzYzNmZlMGE0Y2I2MDVjZjNiNzdiZThmZDgwMDQzZWQyYjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xi_OEdFK4JcYAY9Pzxle4QWeLT3w-F7RnuvLvVOBzg0)

@zhou186  这个您需要在上一层目录执行 `python demo/demo.py`即可

**Comment by zhou186** [comment]
> > > > > 当我在远程服务器上运行 /Ask-Anything-main/video_chat2/tasks/train_qformer.py 时，它说 ModuleNotFoundError： No module named 'dataset'。但是，代码中没有错误或警告，并且代码路径是正确的。
> > > > 
> > > > 
> > > > 请问解决了吗
> > > 
> > > 
> > > 您遇到类似的问题了吗？我想上面的回答应该可以解决这个问题[#225 （comment）](https://github.com/OpenGVLab/Ask-Anything/issues/225#issuecomment-2302083025)
> > > 您好，正在运行的路径确实位于video_chat2文件夹下，我在远程服务器上运行的demo.py文件，报错ModuleNotFoundError: No module named 'dataset'。翻了翻文件夹，确实没有找到dataset
> > > ![1](https://private-user-images.githubusercontent.com/137672318/360319769-00c0ebcb-d985-4ea2-94c8-d1ed0cb646bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTAxOTYsIm5iZiI6MTcyNDMwOTg5NiwicGF0aCI6Ii8xMzc2NzIzMTgvMzYwMzE5NzY5LTAwYzBlYmNiLWQ5ODUtNGVhMi05NGM4LWQxZWQwY2I2NDZiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNjU4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2VmZGJkYWYzM2JmZDBmZThhYjM0YzVlYWYwNzYzNmZlMGE0Y2I2MDVjZjNiNzdiZThmZDgwMDQzZWQyYjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xi_OEdFK4JcYAY9Pzxle4QWeLT3w-F7RnuvLvVOBzg0)
> 
> @zhou186 这个您需要在上一层目录执行 `python demo/demo.py`即可

非常感谢您的回复，但我又遇到一个新问题
返回上一级运行demo.py后报错ModuleNotFoundError: No module named 'model'
video_chat2文件夹里似乎只有models，且models里没有需要导入的VideoChat2_it_vicuna
![4](https://github.com/user-attachments/assets/6a62bca4-5051-4b78-875f-5675f349a46d)
![2](https://github.com/user-attachments/assets/9e87cd1c-bdbd-44f5-92a6-c92e320c1c74)
![3](https://github.com/user-attachments/assets/c559756f-cc78-4b63-8b1f-637eb265e88e)

**Comment by yinanhe** [comment]
@zhou186 应该是有的，还请您再试试
https://github.com/OpenGVLab/Ask-Anything/blob/37db036dfc7e8188ab0411691070c643cd21f7b6/video_chat2/demo/demo.py#L11

它来自于：
https://github.com/OpenGVLab/Ask-Anything/blob/37db036dfc7e8188ab0411691070c643cd21f7b6/video_chat2/models/__init__.py#L4

**Comment by zhou186** [comment]
> @zhou186 应该是有的，还请您再试试
> 
> https://github.com/OpenGVLab/Ask-Anything/blob/37db036dfc7e8188ab0411691070c643cd21f7b6/video_chat2/demo/demo.py#L11
> 
> 它来自于：
> 
> https://github.com/OpenGVLab/Ask-Anything/blob/37db036dfc7e8188ab0411691070c643cd21f7b6/video_chat2/models/__init__.py#L4

非常感谢您的回复，请问可以添加一下您的联系方式吗，在这上面回复消息有些慢

**Comment by yinanhe** [comment]
![6c4076e57cf347203d22309656904a4](https://github.com/user-attachments/assets/096d7163-a5d4-4710-8ce9-5bea042dff1f)

**Comment by zhou186** [comment]
> ![6c4076e57cf347203d22309656904a4](https://private-user-images.githubusercontent.com/43169235/360328829-096d7163-a5d4-4710-8ce9-5bea042dff1f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTE4NTMsIm5iZiI6MTcyNDMxMTU1MywicGF0aCI6Ii80MzE2OTIzNS8zNjAzMjg4MjktMDk2ZDcxNjMtYTVkNC00NzEwLThjZTktNWJlYTA0MmRmZjFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3MjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMWRiMDA5OGE0Yzc5NmMwMmY4OWU2OGM1MDIxNWU2NWVhNzQ4ZjFhOTg0NzI5MTQ3ZDQ1M2EyMTg1YTcxZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bNaUi4aZu7f79Gd8po5XGnvOK-J3Vg57wt8sIf3sAQ)

谢谢！
