### ISSUE TITLE
Why is the output garbled

### ISSUE THREAD

**Issue by Graysonicc** [OpenGVLab/Ask-Anything#226]
![image](https://github.com/user-attachments/assets/5abdeb51-0213-40c2-9c87-4cd22c79bdd0)

**Comment by yinanhe** [comment]
From the screenshot, it seems that you are using the vicuna version of the videochat model. Please ensure that the weights of your vicuna-7b-v0 are loaded correctly.

Load the correct weight you can refer to https://github.com/OpenGVLab/Ask-Anything/issues/224#issuecomment-2301333331
