### ISSUE TITLE
What does this code mean

### ISSUE THREAD

**Issue by Graysonicc** [OpenGVLab/Ask-Anything#228]
![image](https://github.com/user-attachments/assets/4c8a562c-a8ef-4b1f-a393-62bd3c7a0f8c)

**Comment by yinanhe** [comment]
This is estimating the accuracy of random choices, and the accuracy of each question is the reciprocal of the number of options

**Comment by yinanhe** [comment]
Hi, we will close this issue. Feel free to contact us if you have other questions.
