### ISSUE TITLE
Release of GPT scripts to generate the QA data for MVBench

### ISSUE THREAD

**Issue by BennoKrojer** [OpenGVLab/Ask-Anything#229]
Hello,

Thanks for releasing MVBench and all the other great things! I am studying video understanding benchmarks in my research and was wondering if you could release the scripts/prompts for QA generation with GPT, e.g. for CLEVERER or Action Antonym?

Your help would be much appreciated! Even just the raw scripts+prompts I could work with.

Best,
Benno

**Comment by Andy1621** [comment]
Thanks for your great interest. Acutally, most of the QAs are generated by template. For example, the `Action Antonym` is builted on [PAXION](https://github.com/MikeWangWZHL/Paxion). We design the options and simply use GPT to generate simple questions.

One special example is `Unexpected Action`, I used ChatGPT to generate multiple-choice options from simple QA. The prompt is modified from [FunQA](https://funqa-benchmark.github.io/).

**Comment by yinanhe** [comment]
Hi, we will close this issue. Feel free to contact us if you have other questions.
