### ISSUE TITLE
怎么进去微信或者Q交流群?

### ISSUE THREAD

**Issue by lwm345** [OpenGVLab/Ask-Anything#230]
How can I join a WeChat or QQ group chat? The previous QR code has expired.

**Comment by yinanhe** [comment]
您可以通过扫描下方二维码加群，或者联系GV小助手加群

![4ea97e8696f51668665d28078c650f5](https://github.com/user-attachments/assets/fda6c33e-05a6-46ff-aea3-09c9bc27dd6a)
![ee1fc2949f4f3e7a8c902ec4ce79916](https://github.com/user-attachments/assets/001c7eba-9633-4a48-9dc1-2f6c95cf1a0e)
