### ISSUE TITLE
 running video_chat2

### ISSUE THREAD

**Issue by dante0shy** [OpenGVLab/Ask-Anything#231]
Hi, really thanks for the work. Some links in the instructions of video_chat2 seem to be down, eg. [UMT-L/16](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/l16_25m.pth) and [model](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/umt_l16_qformer.pth). As the demo code will load these ckpt. Can you update these links or maybe google drive links?

**Comment by yinanhe** [comment]
Hi, they are moved to huggingface:
https://huggingface.co/OpenGVLab/videochat/resolve/main/umt_l16_qformer.pth
https://huggingface.co/OpenGVLab/VideoChat2_stage2_Mistral_7B
https://huggingface.co/OpenGVLab/VideoChat2_stage3_Mistral_7B
https://huggingface.co/OpenGVLab/VideoChat2_HD_stage4_Mistral_7B

**Comment by dante0shy** [comment]
Thx a lot.
