### ISSUE TITLE
download links for the datasets

### ISSUE THREAD

**Issue by XduSyL** [OpenGVLab/Ask-Anything#233]
Thank you for the excellent work! If I want to reproduce your results, I would first need to download the datasets for stage 1, stage 2, and stage 3. However, I couldn’t find the download links for the datasets, and I would greatly appreciate it if you could provide the links along with the directory tree structure of the dataset after downloading.

**Comment by yinanhe** [comment]
Hi, in stage1 and stage2, the data we use comes from the public datasets WebVid10M, CC3M, CC12M, COCO, VG, SBU, [InternVid-1M](https://opendatalab.com/vd-foundation/InternVid-10M-FLT), you can download it yourself and adjust the https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/configs/data.py according to your data organization format; the data used in stage3 has been listed in [data.md](https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/DATA.md) for your reference.

**Comment by XduSyL** [comment]
After downloading these public datasets, can I train the model using the original format of the public data, or do I need to preprocess the data into a specific format before training?

**Comment by yinanhe** [comment]
You can directly use the downloaded data for training, but the meta file needs to be consistent with our data json format. You can refer to the format https://huggingface.co/datasets/OpenGVLab/VideoChat2-IT

**Comment by yinanhe** [comment]
Hi, we will close this issue. Feel free to contact us if you have other questions.
