### ISSUE TITLE
请大佬教一下怎么在自己的电脑上训练

### ISSUE THREAD

**Issue by JiamingHuHu** [OpenGVLab/Ask-Anything#234]
大佬您好，我看到stage1，不太理解set pretrained in stage1_config该怎么设置，点进去后是404 Not Found。在.sh文件中看到一些设置后，请问用bash命令行的意思是只能在服务器上运行，不能在个人电脑上运行吗？

**Comment by yinanhe** [comment]
您好，修正了这个链接，实际访问地址为：https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/scripts/videochat_vicuna/config_7b_stage1.py

个人电脑如果安装了pytorch等依赖环境也是可以运行的，具体参考https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/scripts/videochat_vicuna/run_7b_stage1.sh

**Comment by JiamingHuHu** [comment]
请问bash脚本里tasks/train_qformer.py这一段怎么改呀？

**Comment by yinanhe** [comment]
不需要改

**Comment by JiamingHuHu** [comment]
run_7b_stage1.sh: line 20: srun: command not found
我运行时提示该错误

**Comment by yinanhe** [comment]
https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/scripts/videochat_vicuna/run_7b_stage1.sh  这里没有这句话，您发的是slurm_run_7b_stage1.sh

**Comment by JiamingHuHu** [comment]
我是在conda环境中运行的，在bash脚本前面加了如下三行代码
source D:/anaconda3/etc/profile.d/conda.sh
conda activate py39
set -ex
现在又出现了下面这个错误，请问该怎么解决呢？
ImportError: cannot import name 'MetaLoader' from 'dataset' (D:\anaconda3\envs\py39\lib\site-packages\dataset\__init__.py)

**Comment by yinanhe** [comment]
请确保运行路径在video_chat2文件夹下，并确保你安装的 dataset 包是最新版本。可以使用以下命令更新它：
pip install --upgrade dataset

**Comment by JiamingHuHu** [comment]
from dataset import MetaLoader, create_dataset, create_loader, create_sampler
ImportError: cannot import name 'MetaLoader' from 'dataset' (D:\anaconda3\envs\py39\lib\site-packages\dataset\__init__.py)
我试了，它又出现这个问题

**Comment by yinanhe** [comment]
您试试卸载dataset这个包呢，https://github.com/OpenGVLab/Ask-Anything/tree/main/video_chat2/dataset

**Comment by JiamingHuHu** [comment]
我卸载./video_chat2/dataset这个文件夹的话还是上面的问题
我pip uninstall datast后的话是No module named 'dataset'

**Comment by yinanhe** [comment]
您的运行路径在video_chat2文件夹下吗

**Comment by JiamingHuHu** [comment]
在呀，我bash文件全部如下，我用cd把它导到这个文件夹里了
source D:/anaconda3/etc/profile.d/conda.sh
conda activate py39
set -ex
cd D:/PyProject/video_chat2/Ask-Anything-main/video_chat2

#!/bin/bash
# Please modify the ${MASTER_NODE}:${MASTER_PORT}
MASTER_NODE=127.0.0.1 
MASTER_PORT=0  # MASTER_PORT=$((10000 + $RANDOM % 100))
NNODE=1
NUM_GPUS=1
OUTPUT_DIR="$(dirname $0)/$JOB_NAME"


torchrun --rdzv_endpoint=${MASTER_NODE}:${MASTER_PORT} \
    --nnodes=${NNODE} \
    --nproc_per_node=${NUM_GPUS} \
    --rdzv_backend=c10d \
    tasks/train_qformer.py \
    $(dirname $0)/config_7b_stage1.py \
    output_dir ${OUTPUT_DIR}

**Comment by JiamingHuHu** [comment]
在呀，我bash文件全部如下，我用cd把它导到这个文件夹里了
`source D:/anaconda3/etc/profile.d/conda.sh
conda activate py39
set -ex
cd D:/PyProject/GUI_keti/video_chat2/Ask-Anything-main/video_chat2

#!/bin/bash
# Please modify the ${MASTER_NODE}:${MASTER_PORT}
MASTER_NODE=127.0.0.1 
MASTER_PORT=0  # MASTER_PORT=$((10000 + $RANDOM % 100))
NNODE=1
NUM_GPUS=1
OUTPUT_DIR="$(dirname $0)/$JOB_NAME"


torchrun --rdzv_endpoint=${MASTER_NODE}:${MASTER_PORT} \
    --nnodes=${NNODE} \
    --nproc_per_node=${NUM_GPUS} \
    --rdzv_backend=c10d \
    tasks/train_qformer.py \
    $(dirname $0)/config_7b_stage1.py \
    output_dir ${OUTPUT_DIR}`

**Comment by yinanhe** [comment]
您直接在`D:/PyProject/GUI_keti/video_chat2/Ask-Anything-main/video_chat2`的路径下 `bash scripts/videochat_vicuna/run_7b_stage1.sh` 试试呢

**Comment by JiamingHuHu** [comment]
![2](https://github.com/user-attachments/assets/e28c8afb-3ddb-47f6-bea7-d91ec6a5e4d5)
还是一样的，一直提示cannot import name 'MetaLoader' from 'dataset'

**Comment by yinanhe** [comment]
MetaLoader存在于https://github.com/OpenGVLab/Ask-Anything/blob/c3f07988b1db77ed24d706650d3cb23e3495a011/video_chat2/dataset/__init__.py#L7 请检查本地环境是否有冲突，如果可能的话报错可以贴的全一点

**Comment by JiamingHuHu** [comment]
![image](https://github.com/user-attachments/assets/807e6a2a-4382-45ee-8cfd-3d99fa5f5d3c)
感觉它老是识别不到dataset那个文件夹

**Comment by yinanhe** [comment]
您可以通过添加以下几行代码在代码最前面来观察当前环境
```
import sys
print(sys.path)
```

**Comment by JiamingHuHu** [comment]
试了下，激活canda环境后工作目录就被定位到D:\anaconda3\envs\py39去了，用cd改目录没反应

**Comment by JiamingHuHu** [comment]
试了下，激活canda环境后，train_qformer.py的工作目录就被定位到D:\anaconda3\envs\py39去了，这咋改回来呀

**Comment by JiamingHuHu** [comment]
它的输出是这样的，里面没有dataset，请问我应该怎么修改呢？
['D:\\PyProject\\GUI_keti\\video_chat2\\Ask-Anything-main\\video_chat2\\tasks', 'D:\\anaconda3\\envs\\py39\\python39.zip', 'D:\\anaconda3\\envs\\py39\\DLLs', 'D:\\anaconda3\\envs\\p
y39\\lib', 'D:\\anaconda3\\envs\\py39', 'D:\\anaconda3\\envs\\py39\\lib\\site-packages', 'D:\\anaconda3\\envs\\py39\\lib\\site-packages\\win32', 'D:\\anaconda3\\envs\\py39\\lib\\site-packages\\win32\\lib', 'D:\\anaconda3\\envs\\py39\\lib\\site-packages\\Pythonwin']

**Comment by JiamingHuHu** [comment]
train_qformer.py的输出是这样的，里面没有dataset，请问我应该怎么修改呢？
['D:\PyProject\GUI_keti\video_chat2\Ask-Anything-main\video_chat2\tasks', 'D:\anaconda3\envs\py39\python39.zip', 'D:\anaconda3\envs\py39\DLLs', 'D:\anaconda3\envs\p
y39\lib', 'D:\anaconda3\envs\py39', 'D:\anaconda3\envs\py39\lib\site-packages', 'D:\anaconda3\envs\py39\lib\site-packages\win32', 'D:\anaconda3\envs\py39\lib\site-packages\win32\lib', 'D:\anaconda3\envs\py39\lib\site-packages\Pythonwin']

**Comment by JiamingHuHu** [comment]
![image](https://github.com/user-attachments/assets/4a3a4096-58b4-4198-8209-d7fa074d0aeb)
我解决上面的问题后，又出现了这个新的问题，我搜网上说nccl不支持windows是吗?

**Comment by yinanhe** [comment]
> train_qformer.py的输出是这样的，里面没有dataset，请问我应该怎么修改呢？ ['D:\PyProject\GUI_keti\video_chat2\Ask-Anything-main\video_chat2\tasks', 'D:\anaconda3\envs\py39\python39.zip', 'D:\anaconda3\envs\py39\DLLs', 'D:\anaconda3\envs\p y39\lib', 'D:\anaconda3\envs\py39', 'D:\anaconda3\envs\py39\lib\site-packages', 'D:\anaconda3\envs\py39\lib\site-packages\win32', 'D:\anaconda3\envs\py39\lib\site-packages\win32\lib', 'D:\anaconda3\envs\py39\lib\site-packages\Pythonwin']

@JiamingHuHu  sys.path.insert(0,'D:\PyProject\GUI_keti\video_chat2\Ask-Anything-main\video_chat')可以缓解您的问题

**Comment by yinanhe** [comment]
> ![image](https://private-user-images.githubusercontent.com/53883748/364733300-4a3a4096-58b4-4198-8209-d7fa074d0aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzIyODEsIm5iZiI6MTcyNTUzMTk4MSwicGF0aCI6Ii81Mzg4Mzc0OC8zNjQ3MzMzMDAtNGEzYTQwOTYtNThiNC00MTk4LTgyMDktZDdmYTA3NGQwYWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwMjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4OGQwMzhlODEyMWQwZTQxYjU0NWFhOTQ0YjFjODlmMWZlNDQwYTI5MmFhNWU0YzI4NGY3M2UyYzRhODU0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vHnrIYDV61SMROhho96a3ALbLi09Jm5fDhCp9U3HmVk) 我解决上面的问题后，又出现了这个新的问题，我搜网上说nccl不支持windows是吗?

@JiamingHuHu 您的本机有装CUDA和GPU版本的pytorch吗

**Comment by JiamingHuHu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/53883748/364733300-4a3a4096-58b4-4198-8209-d7fa074d0aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzIyODEsIm5iZiI6MTcyNTUzMTk4MSwicGF0aCI6Ii81Mzg4Mzc0OC8zNjQ3MzMzMDAtNGEzYTQwOTYtNThiNC00MTk4LTgyMDktZDdmYTA3NGQwYWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwMjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4OGQwMzhlODEyMWQwZTQxYjU0NWFhOTQ0YjFjODlmMWZlNDQwYTI5MmFhNWU0YzI4NGY3M2UyYzRhODU0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vHnrIYDV61SMROhho96a3ALbLi09Jm5fDhCp9U3HmVk) 我解决上面的问题后，又出现了这个新的问题，我搜网上说nccl不支持windows是吗?
> 
> @JiamingHuHu 您的本机有装CUDA和GPU版本的pytorch吗

晚上好，我都装了的，我能在本机上成功运行demo.py，但现在想训练模型就开始一步一个坑了

**Comment by yinanhe** [comment]
windows上我们没有尝试过，这个可能您还得多翻翻看windows相关的或者考虑在WSL上训练

**Comment by JiamingHuHu** [comment]
这样吗，那我去了解一下wsl。请问怎么直观地看这个模型里面的具体结构呀

**Comment by JiamingHuHu** [comment]
作者您好，我现在用wsl了，请问图中指的一些模块av, decord, einops等都是pip安装的吗，还是在某个文件中自定义的，因为我在安装了requirements.txt中的所有模块后运行run_7b_stage1.sh后，提示ModuleNotFoundError: No module named 'av'

**Comment by JiamingHuHu** [comment]
作者您好，我现在用wsl了，请问图中指的一些模块av, decord, einops等都是pip安装的吗，还是在某个文件中自定义的，因为我在安装了requirements.txt中的所有模块后运行run_7b_stage1.sh后，提示ModuleNotFoundError: No module named 'av'
![Uploading image.png…]()

**Comment by yinanhe** [comment]
是的，这些需要使用pip安装

**Comment by JiamingHuHu** [comment]
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.
我现在又一直遇到上面这个问题，我在网上搜了一下，我把bert-base-uncased下载到本地提示缺少vocab(明明文件夹里有)，降低transformers版本以解决这个问题却又出现版本不兼容的问题。
请问我该怎么做呢

**Comment by JiamingHuHu** [comment]
retrieval_utils.py中下面这一行代码返回的是None，请问该怎么改呢
text_encoder = model.get_text_encoder()

**Comment by yinanhe** [comment]
> OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer. 我现在又一直遇到上面这个问题，我在网上搜了一下，我把bert-base-uncased下载到本地提示缺少vocab(明明文件夹里有)，降低transformers版本以解决这个问题却又出现版本不兼容的问题。 请问我该怎么做呢

不需要降低transformers的版本，并且您的当前运行路径下不要有bert-base-uncased的文件夹，如果可以直接链接hf可以 考虑直接从hf上拉，如果不能可以完整的clone下文件夹并把路径改过去

**Comment by yinanhe** [comment]
> retrieval_utils

这部分的代码是做retrieval的，应该用不上

**Comment by JiamingHuHu** [comment]
for i, (media_type, (image, text, instruction, _)) in enumerate(iterator):
在stage2中，上面这个语句比stage1多了一个instruction，但iterator的生成在两个阶段都是一模一样的，使得上面这个语句出错，Error: got 3 expected 4。
请问是代码的问题吗，我详细看了下取数据的方式，在pt_datasets.py中，get_anno 只返回了数据集的filename、caption
![image](https://github.com/user-attachments/assets/c9817be2-c14f-4872-9ab3-0651de108215)
请问要运行stage2的话，意思是要自己在这里面添加instruction的语句吗？

**Comment by JiamingHuHu** [comment]
for i, (media_type, (image, text, instruction, _)) in enumerate(iterator):
在stage2中，上面这个语句比stage1多了一个instruction，但iterator的生成在两个stage中都是一模一样的，使得上面这个语句出错，Error: got 3 expected 4。
请问是代码的问题吗，我详细看了下取数据的方式，在pt_datasets.py中，这里只返回了数据集的filename、caption、index
![image](https://github.com/user-attachments/assets/2300f633-4729-43f5-9b5d-0bc031420cae)
请问要运行stage2的话，意思是要自己在这里面添加instruction的语句吗？

**Comment by JiamingHuHu** [comment]
for i, (media_type, (image, text, instruction, _)) in enumerate(iterator):
在stage2中，上面这个语句比stage1多了一个instruction，但iterator的生成在两个stage中都是一模一样的，使得上面这个语句出错，Error: got 3 expected 4。
请问是代码的问题吗，我详细看了下取数据的方式，在pt_datasets.py中，这里只返回了数据集的image、caption、index
![image](https://github.com/user-attachments/assets/4d60d2b2-e61b-4f1e-81c2-cdd5b6c1048e)
请问要运行stage2的话，意思是要自己在这里面添加instruction的语句吗？

**Comment by JiamingHuHu** [comment]
> > OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer. 我现在又一直遇到上面这个问题，我在网上搜了一下，我把bert-base-uncased下载到本地提示缺少vocab(明明文件夹里有)，降低transformers版本以解决这个问题却又出现版本不兼容的问题。 请问我该怎么做呢
> 
> 不需要降低transformers的版本，并且您的当前运行路径下不要有bert-base-uncased的文件夹，如果可以直接链接hf可以 考虑直接从hf上拉，如果不能可以完整的clone下文件夹并把路径改过去

感谢回答，我主要到初始化模型中有好几个地方都用到了tokenizer，请问我将tokenizer下载到本地后，它们可以共用同一个tokenizer吗

**Comment by yinanhe** [comment]
> > > OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer. 我现在又一直遇到上面这个问题，我在网上搜了一下，我把bert-base-uncased下载到本地提示缺少vocab(明明文件夹里有)，降低transformers版本以解决这个问题却又出现版本不兼容的问题。 请问我该怎么做呢
> > 
> > 
> > 不需要降低transformers的版本，并且您的当前运行路径下不要有bert-base-uncased的文件夹，如果可以直接链接hf可以 考虑直接从hf上拉，如果不能可以完整的clone下文件夹并把路径改过去
> 
> 感谢回答，我主要到初始化模型中有好几个地方都用到了tokenizer，请问我将tokenizer下载到本地后，它们可以共用同一个tokenizer吗

可以的
