### ISSUE TITLE
videochat2可以同时输入多个视频然后进行处理，以供下游任务吗？

### ISSUE THREAD

**Issue by Graysonicc** [OpenGVLab/Ask-Anything#237]
如果直接使用开源的videochat2同时处理多个视频的任务，效果会怎么样，在不进行重训练的条件下效果预计怎样？我之前尝试过，发现模型只会关注最后的那段视频，前面的视频内容好像会被忽略。

**Comment by yinanhe** [comment]
我们的训练都是单个视频，多轮对话没有多个视频的数据训练。
