### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by Graysonicc** [OpenGVLab/Ask-Anything#242]
在运行bash scripts/videochat_vicuna/run_7b_stage3.sh时候出现这个问题，请问如何解决：
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

**Comment by aries2004-bit** [comment]
try this

https://bit.ly/4eugCty

you may need to install the c compiler
