### ISSUE TITLE
Cannot install -r requirements.txt (line 6) and transformers==4.28.0 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by jelleheijne1997** [OpenGVLab/Ask-Anything#25]
ERROR: Cannot install -r requirements.txt (line 6) and transformers==4.28.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested transformers==4.28.0
    simplet5 0.1.4 depends on transformers==4.16.2
    The user requested transformers==4.28.0
    simplet5 0.1.3 depends on transformers==4.10.0
    The user requested transformers==4.28.0
    simplet5 0.1.2 depends on transformers==4.6.1
    The user requested transformers==4.28.0
    simplet5 0.1.1 depends on transformers==4.8.2
    The user requested transformers==4.28.0
    simplet5 0.1.0 depends on transformers==4.6.1
    The user requested transformers==4.28.0
    simplet5 0.0.9 depends on transformers==4.6.1
    The user requested transformers==4.28.0
    simplet5 0.0.7 depends on transformers==4.6.1

How do I fix this? I use Python 3.8.16

**Comment by yinanhe** [comment]
You can install the `transformers==4.16.2`

**Comment by koshyviv** [comment]
> You can install the transformers==4.16.2

This will still create a problem while running later on. 
Once all installations are complete you can install `transformers==4.28.0` again, there would be a conflict but wouldn't impact your workflow anymore.

**Comment by yinanhe** [comment]
Thanks for your feedback! If you still have any problems, please feel free to reopen this issue.
