### ISSUE TITLE
Videochat 2 IT dataset size

### ISSUE THREAD

**Issue by joslefaure** [OpenGVLab/Ask-Anything#250]
I know that's a long shot, but has anyone downloaded the whole dataset and can tell me how much GB/TB I can expect it to be? Thank you

**Comment by yinanhe** [comment]
kinetics 400 436G / 600  727G / 700 867G
[VideoChatGPT](https://mbzuaiac-my.sharepoint.com/personal/hanoona_bangalath_mbzuai_ac_ae/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fhanoona%5Fbangalath%5Fmbzuai%5Fac%5Fae%2FDocuments%2FVideo%2DChatGPT%2FData%5FCode%5FModel%5FRelease%2FData&ga=1) ~150G
[M3IT](https://huggingface.co/datasets/MMInstruction/M3IT) 29.8 G
[NExTQA](https://drive.google.com/file/d/1jTcRCrVHS66ckOUfWRb-rXdzJ52XAWQH/view)  23G
[CLEVERER](http://data.csail.mit.edu/clevrer/videos/train/video_train.zip) 11.5G 
[YouCook2(only videochat2 processed)](https://huggingface.co/datasets/ynhe/videochat2_data/tree/main) 60G
[TextVR](https://drive.google.com/file/d/1RZefU1XqODCt2NH68P0V_DMAOiQjRlSn/view?usp=share_link) 5.4G
[TGIF](https://github.com/raingo/TGIF-Release/archive/master.zip)  11.8M
[EgoQA(only videochat2 processed)](https://huggingface.co/datasets/ynhe/videochat2_data/blob/main/egoqa_split_videos.zip)  3.68G
[WebVid(non-official)](https://huggingface.co/datasets/TempoFunk/webvid-10M) 20TB
[VideoChat-Conversation-video] (https://huggingface.co/datasets/ynhe/videochat2_data/blob/main/videochat2_conversation_videos.zip) 17.2G

**Comment by joslefaure** [comment]
Thank you so much ☺️
