### ISSUE TITLE
Dependency conflict on click for detectron2

### ISSUE THREAD

**Issue by atxcowboy** [OpenGVLab/Ask-Anything#26]
When installing detectron2 on video_chat_with_MOSS I get:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
typer 0.3.2 requires click<7.2.0,>=7.1.1, but you have click 8.1.3 which is incompatible.

After downgrading click to 7.1.1 I get:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
black 23.3.0 requires click>=8.0.0, but you have click 7.1.1 which is incompatible.

**Comment by yinanhe** [comment]
In our `typer-0.3.2`, it's requirement is  `click<9.0.0,>=7.1.1`

**Comment by yinanhe** [comment]
Due to the lack of updates for a long time, your issue has been temporarily closed. If you still have any problems, please feel free to reopen this issue.
