### ISSUE TITLE
OOM / VRAM requirement?

### ISSUE THREAD

**Issue by atxcowboy** [OpenGVLab/Ask-Anything#27]
Hello,

how much VRAM does this need?

I am getting OOM on my 3090 GPU w/ 24GB on the video_chat_with_MOSS.

OutOfMemoryError: CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 24.00 GiB total capacity; 22.78 GiB already
allocated; 0 bytes free; 22.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by yinanhe** [comment]
We test it on A100-80G, it will take about 50G VRAM.

**Comment by DL-ML** [comment]
> We test it on A100-80G, it will take about 50G VRAM. Maybe you can consider use MOSS-INT4

Is A100-40G okay if we reduce some parameters value?

**Comment by GXYM** [comment]
> > We test it on A100-80G, it will take about 50G VRAM. Maybe you can consider use MOSS-INT4
> 
> Is A100-40G okay if we reduce some parameters value?

how many A100-80G  did you use for the one stage of pre-training?

**Comment by yinanhe** [comment]
> > We test it on A100-80G, it will take about 50G VRAM. Maybe you can consider use MOSS-INT4
> 
> Is A100-40G okay if we reduce some parameters value?

Yes, A10040G card can inference in FP16 mode.

**Comment by yinanhe** [comment]
> > > We test it on A100-80G, it will take about 50G VRAM. Maybe you can consider use MOSS-INT4
> > 
> > 
> > Is A100-40G okay if we reduce some parameters value?
> 
> how many A100-80G did you use for the one stage of pre-training?

32

**Comment by yinanhe** [comment]
Due to the lack of updates for a long time, your issue has been temporarily closed. If you still have any problems, please feel free to reopen this issue.
