### ISSUE TITLE
RuntimeError: checkpoint url or path is invalid

### ISSUE THREAD

**Issue by kushagraagent47** [OpenGVLab/Ask-Anything#30]
(base) ubuntu@ip-172-31-34-181:~/Ask-Anything/video_chat_with_MOSS$ python app.py
/home/ubuntu/miniconda3/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/home/ubuntu/Ask-Anything/video_chat_with_MOSS/app.py", line 21, in <module>
    model = tag2text_caption(pretrained="pretrained_models/tag2text_swin_14m.pth", image_size=image_size, vit='swin_b' )
  File "/home/ubuntu/Ask-Anything/video_chat_with_MOSS/models/tag2text.py", line 225, in tag2text_caption
    model,msg = load_checkpoint_swinbase(model,pretrained,kwargs)
  File "/home/ubuntu/Ask-Anything/video_chat_with_MOSS/models/tag2text.py", line 412, in load_checkpoint_swinbase
    raise RuntimeError('checkpoint url or path is invalid')
RuntimeError: checkpoint url or path is invalid

Facing this issue, not able to fix this

**Comment by yinanhe** [comment]
you should download `tag2text_swin_14m.pth` and put it in `pretrained_models/`

```
wget https://huggingface.co/spaces/xinyu1205/Tag2Text/resolve/main/tag2text_swin_14m.pth ./pretrained_models/tag2text_swin_14m.pth
```
