### ISSUE TITLE
Can't install detectron2.0

### ISSUE THREAD

**Issue by SKBL5694** [OpenGVLab/Ask-Anything#31]
I follow the instruction below:
**conda create -n chatvideo python=3.8.16
conda activate chatvideo

# Clone the repository:
git clone https://github.com/OpenGVLab/Ask-Anything.git
cd ask-anything/video_chat

# Install dependencies:
pip install -r requirements.txt
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'**

But when I run python -m pip install 'git+https://github.com/facebookresearch/detectron2.git',  It raise an error like this:
 **Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/home/xxx/anaconda3/envs/chatvideo/lib/python3.8/site-packages/torch/__init__.py", line 172, in _load_global_dep                                              s
          ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/home/xxx/anaconda3/envs/chatvideo/lib/python3.8/ctypes/__init__.py", line 373, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: /home/xxx/anaconda3/envs/chatvideo/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.1                                              1: symbol cublasLtHSHMatmulAlgoInit version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-z9sng6cp/setup.py", line 10, in <module>
          import torch
        File "/homexxx/anaconda3/envs/chatvideo/lib/python3.8/site-packages/torch/__init__.py", line 217, in <module>
          _load_global_deps()
        File "/home/xxx/anaconda3/envs/chatvideo/lib/python3.8/site-packages/torch/__init__.py", line 178, in _load_global_dep                                              s
          _preload_cuda_deps()
        File "/home/xxx/anaconda3/envs/chatvideo/lib/python3.8/site-packages/torch/__init__.py", line 158, in _preload_cuda_de                                              ps
          ctypes.CDLL(cublas_path)
        File "/home/xxx/anaconda3/envs/chatvideo/lib/python3.8/ctypes/__init__.py", line 373, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: /home/xxx/anaconda3/envs/chatvideo/lib/python3.8/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublas                                              LtHSHMatmulAlgoInit version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.**

So I go to [detectron2.0 ](https://github.com/facebookresearch/detectron2) to find how install it correctly. But in the page https://github.com/facebookresearch/detectron2/blob/main/INSTALL.md, I find **Install Pre-Built Detectron2 (Linux only)** doesn't match the torch version to this project(1.13 in this and detectron2 pre-built only support 1.8,1.9 and 1.10)
Another way I find in that page to install detectron2 is **Build Detectron2 from Source**, but the first step of it is same as yours **python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'**.
So what should I do? Please give me some help.

**Comment by yinanhe** [comment]
examine your `nvidia-driver` and `cuda` version.

**Comment by SKBL5694** [comment]
Driver Version: 460.106.00, 
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
Since this is a public server, I cannot update its driver and cuda version. So am I unable to try your project?

**Comment by yinanhe** [comment]
Maybe you can use `pip uninstall nvidia_cublas_cu11` to solve the problem.

**Comment by huangbaichao** [comment]
I install detectron2 manually. It worked.
git clone detectron2
cd detectron2
pip install -e .
Maybe you can have a try.

**Comment by yinanhe** [comment]
Due to the lack of updates for a long time, your issue has been temporarily closed. If you still have any problems, please feel free to reopen this issue.
