### ISSUE TITLE
How can I donwload the  videos in the instruction dataset?

### ISSUE THREAD

**Issue by GuoxingY** [OpenGVLab/Ask-Anything#41]
How can I donwload the  videos in the instruction dataset? It seems that there is only json file released?

**Comment by yinanhe** [comment]
The videos in the instruction dataset were re-annotated from [WebVid](https://m-bain.github.io/webvid-dataset/), and you can go to [WebVid](https://m-bain.github.io/webvid-dataset/) to obtain the corresponding download links.

**Comment by gjtjx** [comment]
Data Link 404？where is the descriptions generated by GPT4?

**Comment by yinanhe** [comment]
> Data Link 404？where is the descriptions generated by GPT4?

You can find the data here! https://github.com/OpenGVLab/InternVideo/tree/main/Data/instruction_data

**Comment by XuHu0529** [comment]
I see that the original videos are not provided in the WebVid dataset, so is this part of the data not available?

**Comment by Andy1621** [comment]
Which part of the videos? All the video can be found.

**Comment by XuHu0529** [comment]
I found it. I'm sorry I didn't look carefully before, thank you very much!

**Comment by Andy1621** [comment]
You're welcome. Don't hesitate to open an issue if you meet any problems.
