### ISSUE TITLE
checkpoint url or path is invalid

### ISSUE THREAD

**Issue by rohanblkbox** [OpenGVLab/Ask-Anything#48]
checkpoint url or path is invalid

for video_chat

**Comment by rohanblkbox** [comment]
How to download the checkpoints?

**Comment by yinanhe** [comment]
You can download the checkpoints by following the instruction for [the usage of video_chat](https://github.com/OpenGVLab/Ask-Anything/tree/main/video_chat#running-usage).

**Comment by NiloufarAb** [comment]
Hello, I downloaded both models using the provided commands : 
 - ViT: wget https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pth
- QFormer: wget https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_flant5xxl.pth

However, keep getting the "RuntimeError: checkpoint url or path is invalid" error for q model.

**Comment by abdull6771** [comment]
@NiloufarAb Please do you solve this problem

**Comment by yinanhe** [comment]
@abdull6771 Have you encountered similar problems? Have you filled in the correct checkpoint download address in the config? If you encounter any problems, please feel free to reopen this issue. We also recommend that you experience better [video_chat2](https://github.com/OpenGVLab/Ask-Anything/tree/main/video_chat2) :)
