### ISSUE TITLE
Can I finetune the model on my dataset with 4 * 3090?

### ISSUE THREAD

**Issue by aixiaodewugege** [OpenGVLab/Ask-Anything#50]
Or how much GPU memory is needed at least?

**Comment by Andy1621** [comment]
For 3090, without any technique, it's hard to finetune. However, you can adopt ZERO and low-bit training like [LAVIN](https://github.com/luogen1996/LaVIN/tree/main).

**Comment by aixiaodewugege** [comment]
Thanks for your reply! I will have a look at LAVIN.

I can't finetune with 3090 even by reducing the batchsize ?

**Comment by Andy1621** [comment]
Thanks for your try. Don't forget to update your conclusion after you try LAVIN! It may be helpful to use those techiniques~
