### ISSUE TITLE
How does the model work for audio input?

### ISSUE THREAD

**Issue by Kelsey2018** [OpenGVLab/Ask-Anything#51]
1. pure audio as input
2. audio that accompanies the video

**Comment by Andy1621** [comment]
For audio input, it will require another audio encoder. You can use [BEAT](https://github.com/microsoft/unilm/tree/master/beats) or [ImageBind](https://github.com/facebookresearch/ImageBind). The latter is better since the visual encoder and audio encoder are aligned.

**Comment by Kelsey2018** [comment]
Thanks! In this repo, the code of the audio encoder is not included right? 
And I wonder how to process the audio separated from video? When the audio is converted into text information, how is it aligned with the corresponding image?

**Comment by Andy1621** [comment]
Yes. We do not add an audio encoder in VideoChat_embed, but in VideoChat_text, we use whisper to convert audio into text information, see [here](https://github.com/OpenGVLab/Ask-Anything/tree/long_video_support/).

To process the audio, you can either use ImageBind to process raw audio like [Video-LLaMA](https://github.com/DAMO-NLP-SG/Video-LLaMA/tree/main) or convert it into text like [Macaw-LLM](https://github.com/lyuchenyang/Macaw-LLM).

**Comment by Kelsey2018** [comment]
WOW! 
The point I still have a problem with is, as you stated in your paper, "We then consolidate related content in the captions considering the timing and generate a timestamped video text description". Does it mean that after the audio is encoded into text information, it is combined with the text information extracted from the video?

**Comment by Andy1621** [comment]
Sorry for the late response. Yes, we combine the text information from different vision and audio foundation models together.

**Comment by Kelsey2018** [comment]
OOOOk! Thank you very much! Your work is awesome!
