### ISSUE TITLE
Stage 1 training datasets format

### ISSUE THREAD

**Issue by crqcrq001** [OpenGVLab/Ask-Anything#52]
Sorry I am new to this repo. If I want to reproduce stage1, how can I prepare training dataset.Similar question as

[https://github.com/OpenGVLab/Ask-Anything/issues/46](url)

**Comment by crqcrq001** [comment]
https://github.com/OpenGVLab/Ask-Anything/issues/46#issue-1754442730

**Comment by Andy1621** [comment]
The format is the same as in [ALBEF](https://github.com/salesforce/ALBEF) and [VindLU](https://github.com/klauscc/VindLU/tree/main).
```python
image_data = [
  {'image': image_path, 'caption': caption_content},
  {'image': image_path, 'caption': caption_content},
]
video_data = [
  {'video': video_path, 'caption': caption_content},
  {'video': video_path, 'caption': caption_content},
]
```
You can find the example [here](https://drive.google.com/drive/folders/12bC7WotvwyTG4pVvYeU4iZzmBLP1-6d9).
