### ISSUE TITLE
Video Caption Model

### ISSUE THREAD

**Issue by yinkangning0124** [OpenGVLab/Ask-Anything#54]
Hi,
    Thanks for your great work, I wanna know how can i use the video caption model?

Kangning

**Comment by Andy1621** [comment]
I'm not sure about your specific problem, but to use VideoChat for caption, you can follow the demo in https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat/demo.ipynb

**Comment by yinkangning0124** [comment]
sorry to bother, I wanna ask another question.
When running video_chat_with_ChatGPT/app.py, I got this problem:
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

Could you tell me how to fix it?

**Comment by yinkangning0124** [comment]
I find the solution, that is you should change the torch version to 1.12.1 and the torchvision version to 0.13.1

**Comment by Andy1621** [comment]
Thanks for your try~
