### ISSUE TITLE
请问微信群二维码过期了，能否更新下加入呢？

### ISSUE THREAD

**Issue by yunzhongfei** [OpenGVLab/Ask-Anything#56]
thanks

**Comment by yinanhe** [comment]
![01fb4e697febe9c26649d2328f3dd0b](https://github.com/OpenGVLab/Ask-Anything/assets/43169235/7ce019b0-b8d5-4fc6-91f4-5dabb275c365)

**Comment by fkcptlst** [comment]
又过期了，请问能重新发一下吗？谢谢！
