### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ceyxasm** [OpenGVLab/Ask-Anything#57]
While running demo.py, I am able to initialize the various models but get terminated with the AssertionError.

**Comment by yinanhe** [comment]
How was your torch installed?

**Comment by ceyxasm** [comment]
Makes me think now. 
I feel that I created a conda env without specifying the python version and when I ran `pip install -r requirements.txt`, there was a dependency conflict as `No matching distribution found for torch==1.13.1+cu117`
So I think I manually went ahead with `2.0.1`

PS: which python version shall I use to create my env?

**Comment by ceyxasm** [comment]
Fresh install with `python=3.9` solved the error. Hence closing.
