### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by adeobootpin** [OpenGVLab/Ask-Anything#58]
Hello,

When I run the following command:
python apply_delta.py --base ./llama-13b --target stable-vicuna-13b --delta pvduy/stable-vicuna-13b-delta

I get this error:
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./llama-13b.

Where do I find the missing files? Or did I miss something in a previous step?

Thanks

**Comment by karrymao** [comment]
You may run
```bash
python apply_delta.py \
  --base decapoda-research/llama-13b-hf \
  --target stable-vicuna-13b \
  --delta CarperAI/stable-vicuna-13b-delta
```
It will automatically download (and cache) llama weights from huggingface.
