### ISSUE TITLE
 How to use “chat.generate()” to generate answers in batch

### ISSUE THREAD

**Issue by Summer-seu** [OpenGVLab/Ask-Anything#60]
Thank you for sharing us with your great works! I would like to ask how to use “chat.generate” function in "demo.py" file to generate answers in batch?

**Comment by yinanhe** [comment]
change the `tokenizer.decode` to `tokenizer.batch_decode`

**Comment by yinanhe** [comment]
Due to the lack of updates for a long time, your issue has been temporarily closed. If you still have any problems, please feel free to reopen this issue.
