### ISSUE TITLE
Local Videochat uploading video:Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Yujia-Zhang0913** [OpenGVLab/Ask-Anything#63]
<img width="377" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/73634487/18a2a42d-ffc4-4889-ac11-bd042e88133c">
<img width="960" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/73634487/82a050d4-5826-484f-bb19-428f023be3a1">

Hi, I want to build the videochat locally, but when I tried to upload my video through http://0.0.0.0:7860, there would be an error. And when I run app.py, it seems good. Thx!

<img width="768" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/73634487/6f5cb867-79ff-4c9f-8874-e845702f7fbb">

**Comment by yinanhe** [comment]
Is there any error message in the terminal? Do you have a network proxy?

**Comment by Yujia-Zhang0913** [comment]
> Is there any error message in the terminal? Do you have a network proxy?↳
> 
> If you are running a network proxy, it is recommended to disable it.↳

Thx! I'm using the proxy. I disabled it and it work out.
But I encountered another problem: can this project use gpt-35-turbo-16k? Thx!
<img width="774" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/73634487/c8b9e6a7-3be6-479f-a9e0-dd481d1b9aef">

**Comment by yinanhe** [comment]
Maybe you can change the https://github.com/OpenGVLab/Ask-Anything/blob/6e621d11f7714aa90d047decf6f037bd860598d8/video_chat_with_ChatGPT/chatbot.py#L70C64-L70C87 to  `model_name='gpt-3.5-turbo-16k'`

**Comment by Yujia-Zhang0913** [comment]
> Maybe you can change the https://github.com/OpenGVLab/Ask-Anything/blob/6e621d11f7714aa90d047decf6f037bd860598d8/video_chat_with_ChatGPT/chatbot.py#L70C64-L70C87 to `model_name='gpt-3.5-turbo-16k'`↳
It works out now. I used the model_name='gpt-3.5-turbo-16k. and added an engine(gpt-35-turbo-16k) and a new define class. Really thx!
<img width="319" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/73634487/39055bf3-4846-4d1f-9318-77ea9b78a7a7">

<img width="289" alt="image" src="https://github.com/OpenGVLab/Ask-Anything/assets/73634487/e60a7cdb-7640-4993-bf8b-c3df2b870358">
