### ISSUE TITLE
missing llama-7b-hf and llama-13-hf urls.

### ISSUE THREAD

**Issue by ThreeGold-Jiang** [OpenGVLab/Ask-Anything#72]
the urls in the readme are unreachable

**Comment by yinanhe** [comment]
This may be the case that the author who originally shared the model weights has deleted the repository. You can convert the corresponding checkpoint on your own.

**Comment by yinanhe** [comment]
Due to the lack of updates for a long time, your issue has been temporarily closed. If you still have any problems, please feel free to reopen this issue.
