### ISSUE TITLE
本地部署模型输出乱码

### ISSUE THREAD

**Issue by HaoRanLyu** [OpenGVLab/Ask-Anything#73]
您好，我尝试在本地部署 video chat 模型，使用的是 llama 13b，但是在运行起来做问答的时候模型会输出乱码，请问是什么情况？
![image](https://github.com/OpenGVLab/Ask-Anything/assets/15014097/45884938-a42d-4888-91f1-05a693b89194)

**Comment by yinanhe** [comment]
Thank you for attempting to deploy VideoChat locally. Before deploying the model, please ensure that the weights of LLM have been converted.

**Comment by yinanhe** [comment]
Due to the lack of updates for a long time, your issue has been temporarily closed. If you still have any problems, please feel free to reopen this issue.
