### ISSUE TITLE
在线demo无法使用

### ISSUE THREAD

**Issue by HongliXiao** [OpenGVLab/Ask-Anything#74]
请问可以更新一下在线demo的链接吗，好像用不了了

**Comment by yinanhe** [comment]
Thank you for your attention to our work. However, we regret to inform you that we no longer provide online demos. As our code and models are fully open-source, you can deploy them on your own machine or experience them on online platforms such as Hugging Face/OpenXLab.

**Comment by yinanhe** [comment]
Due to the lack of updates for a long time, your issue has been temporarily closed. If you still have any problems, please feel free to reopen this issue.
