### ISSUE TITLE
asnumpy error in videochat2

### ISSUE THREAD

**Issue by YajieW99** [OpenGVLab/Ask-Anything#76]
Hello! When I run the offline inference of videochat2 using the same environment as videochat, I met the problem in conversation.py:
![Snipaste_2023-12-01_14-36-44](https://github.com/OpenGVLab/Ask-Anything/assets/44310850/1c383b08-46ae-4461-97de-7708ac277e95)

However, it's okay when I run videochat, what went wrong?

**Comment by Andy1621** [comment]
You can simply change `asnumpy` to `numpy`.

**Comment by YajieW99** [comment]
> You can simply change `asnumpy` to `numpy`.

Thanks, already solved.

**Comment by hkunzhe** [comment]
> > You can simply change `asnumpy` to `numpy`.
> 
> Thanks, already solved.

@Andy1621, Why would such a weird error occur? Moreover, there's also asnumpy that can lead to the same issue https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/conversation.py#L116.

**Comment by Andy1621** [comment]
Hi! It is a bug of different numpy versions.
