### ISSUE TITLE
mvbench ssv2 data video file open err

### ISSUE THREAD

**Issue by MarStarck** [OpenGVLab/Ask-Anything#82]
`file open decord err /data/mvbench/video/ssv2_video/2877.webm [11:02:32] /github/workspace/src/video/ffmpeg/threaded_decoder.cc:292: [11:02:32] /github/workspace/src/video/ffmpeg/threaded_decoder.cc:218: Check failed: avcodec_send_packet(dec_ctx_.get(), pkt.get()) >= 0 (-11 vs. 0) Thread worker: Error sending packet.`
about 185 video file cannot open

**Comment by Andy1621** [comment]
Is it an error or a warning? It seems normal in my environment. Could you please list your environment?

**Comment by MarStarck** [comment]
`ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers`

`decord: 0.6.0`

**Comment by Andy1621** [comment]
For me:
```shell
decord                   0.6.0

ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.4.0 (GCC)
```

**Comment by yinanhe** [comment]
@MarStarck  Have you employed the `load_video` function in [mvbench.ipynb](https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/mvbench.ipynb)? I tested it, and there were no errors when using the `read_video` function to read the uploaded ssv2 video.
![image](https://github.com/OpenGVLab/Ask-Anything/assets/43169235/22b2a0ec-52ff-414c-bb4a-500b95759805)

**Comment by MarStarck** [comment]
I have tested the scripts and it's ok. maybe the get_index I modified have something wrong. thks.

**Comment by HGGshiwo** [comment]
in my case, below will failed:

```
vr = decord.VideoReader(str(self.path))
video = vr.get_batch(self._idx)
```

Error:
```
decord._ffi.base.DECORDError: 
[11:26:51] D:\a\decord\decord\src\video\ffmpeg\threaded_decoder.cc:292: 
[11:26:51] D:\a\decord\decord\src\video\ffmpeg\threaded_decoder.cc:218: Check failed: avcodec_send_packet(dec_ctx_.get(), pkt.get()) >= 0 (-11 vs. 0) Thread worker: Error sending packet
```

find out use VidoeReader(path, num_threads=1) to avoid this  error
