### ISSUE TITLE
Ego4d dataset split unavailable

### ISSUE THREAD

**Issue by LiJiaqi96** [OpenGVLab/Ask-Anything#86]
Hi, thanks for your great work of VideoChat2!  
I tried to organize the Ego4d dataset used in the paper. But I found that there are several splits for each video, and the split information is unavailable neither on Ego4d website nor on this repo.  
Is there any information about how the splits were performed? Thanks!  
  
An example (the question is about how to obtain the "split_0.mp4":   
d250521e-5197-44aa-8baa-2f42b24444d2/split_0.mp4

**Comment by Andy1621** [comment]
Please check the original JSON [here](https://drive.google.com/file/d/1PPT6ybmYHcXtz8KC8JnypP5vmzsTviAa/view?usp=sharing). You may need to download the video from Ego4D and split the videos by yourself.

**Comment by LiJiaqi96** [comment]
Thanks for your quick reply!!  
BTW, the same issue occurs in the YouCook2 dataset. I observed that in YouCook2, the split was done by the "segment" in the original json file. Is it the index of frames? Thanks:)

**Comment by Andy1621** [comment]
Yes. The `segment` means the `start second` and `end second`.

**Comment by LiJiaqi96** [comment]
Thanks again for your helpful information!

**Comment by cathyxl** [comment]
Hi @Andy1621 , I found many splits for one video_uid in the ego4f_nlp_qa.json. I'm wondering how you index the splits.  Do splits with earlier video start sec have smaller index numbers?

**Comment by Andy1621** [comment]
@cathyxl I just simply split the video according to the annotations. For the same video_uid, different `clip_start_sec` and `clip_end_sec` will lead to different splits, thus generating split0, split1 and so on.

**Comment by cathyxl** [comment]
> @cathyxl I just simply split the video according to the annotations. For the same video_uid, different `clip_start_sec` and `clip_end_sec` will lead to different splits, thus generating split0, split1 and so on.

Does that mean you decide the index for the clips depending on their appearance order in the annotation file?

**Comment by Andy1621** [comment]
Yes, but actually you can split the clips by yourself and make up the JSON file.

**Comment by cathyxl** [comment]
c

> Yes, but actually you can split the clips by yourself and make up the JSON file.

Can you kindly provide the script to split the ego4d videos? I found there were some errors when splitting these videos. It will affect the performance a lot if the split videos are not matched with the instruction data samples.

**Comment by Andy1621** [comment]
I'm sorry that I can not find the full scripts. However, I find some scripts about `ffmpeg` as follows:
```shell
mkdir -p your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2
ffmpeg -ss 55.8300286 -t 4.4510000000000005 -accurate_seek -i your_path/EgoQA/raw_videos/d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4 -c:v libx264 -c:a aac -strict experimental -an your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2/split_0.mp4
mkdir -p your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2
ffmpeg -ss 62.7295786 -t 9.501449999999984 -accurate_seek -i your_path/EgoQA/raw_videos/d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4 -c:v libx264 -c:a aac -strict experimental -an your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2/split_1.mp4
mkdir -p your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2
ffmpeg -ss 150.5177086 -t 3.9923200000000065 -accurate_seek -i your_path/EgoQA/raw_videos/d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4 -c:v libx264 -c:a aac -strict experimental -an your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2/split_2.mp4
mkdir -p your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2
ffmpeg -ss 7.1810286 -t 1.3579999999999997 -accurate_seek -i your_path/EgoQA/raw_videos/d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4 -c:v libx264 -c:a aac -strict experimental -an your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2/split_3.mp4
mkdir -p your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2
ffmpeg -ss 214.81002859999998 -t 11.640000000000015 -accurate_seek -i your_path/EgoQA/raw_videos/d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4 -c:v libx264 -c:a aac -strict experimental -an your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2/split_4.mp4
mkdir -p your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2
ffmpeg -ss 227.0350286 -t 14.85499999999999 -accurate_seek -i your_path/EgoQA/raw_videos/d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4 -c:v libx264 -c:a aac -strict experimental -an your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2/split_5.mp4
mkdir -p your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2
ffmpeg -ss 254.8062886 -t 8.893740000000008 -accurate_seek -i your_path/EgoQA/raw_videos/d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4 -c:v libx264 -c:a aac -strict experimental -an your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2/split_6.mp4
mkdir -p your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2
ffmpeg -ss 7.5185686 -t 5.502459999999999 -accurate_seek -i your_path/EgoQA/raw_videos/d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4 -c:v libx264 -c:a aac -strict experimental -an your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2/split_7.mp4
mkdir -p your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2
ffmpeg -ss 120.70256859999999 -t 2.3184600000000017 -accurate_seek -i your_path/EgoQA/raw_videos/d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4 -c:v libx264 -c:a aac -strict experimental -an your_path/EgoQA/split_videos/d250521e-5197-44aa-8baa-2f42b24444d2/split_8.mp4
```

**Comment by Andy1621** [comment]
Yes, I just use the `diff` as duration. For your second problem, I have not checked the overlap between different clips, but I think it's normal for one clip to match multiple QAs.

**Comment by cathyxl** [comment]
I find my downloaded ego4d videos are d250521e-5197-44aa-8baa-2f42b24444d2.mp4 instead of  d250521e-5197-44aa-8baa-2f42b24444d2/0.mp4.  Is there any problem?
![image](https://github.com/OpenGVLab/Ask-Anything/assets/8326473/0bc63a5f-cde7-4490-9200-976cfda6b1a1)

**Comment by Andy1621** [comment]
@cathyxl I'm compressing the videos and will upload it later~

**Comment by cathyxl** [comment]
That will be great! Thanks a lot.  Btw, will you also upload videos of other datasets ? I found the downloaded video paths of InterVid are not the same as those in the 1.9M instruction data. Can you also show how to process the InternVid files?

**Comment by Andy1621** [comment]
Yes, I can also upload the part of VideoChat2 conversation~

**Comment by Andy1621** [comment]
@cathyxl For EgoQA videos, download them from this [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/egoqa_split_videos.zip). For VideoChat2 conversation videos, download them from this [link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/videochat2_conversation_videos.zip).

**Comment by cathyxl** [comment]
Thanks a lot! @Andy1621. Btw, I have the same problem with kinetics710. I found my downloaded video paths of kinetics 400, 600 and 700 cannot match these paths in the 1.9M instruction data.  Can you also provide the preprocessing scripts?

**Comment by Andy1621** [comment]
@cathyxl Hi! Please check our raw Kinetics annotation files here.  As for the raw videos, I think you may need to find the related link from the official websites or from [Open DataLab](https://openxlab.org.cn/datasets?keywords=kinetics). It may be illegal for us to share Kinetics Videos directly.

**Comment by cathyxl** [comment]
@Andy1621 I see~I find 51 videos missing in my downloaded files.  I think it might be ok.  Besides, I am also looking into the image paths, I found vqav2, vqav2_chinese, st_vqa, okvqa, okvqa_chinese, aokvqa and imagenet have some or all data paths in the pattern of train/xxxx.jpg(x are numbers), which are not coco image paths nor imagenet paths. Can you share how these image paths are organized?

**Comment by Andy1621** [comment]
Yes. Most of the image files are from [M3IT](https://huggingface.co/datasets/MMInstruction/M3IT). And we transform the base64 (`image_str`) to an image using `img_id`.

**Comment by Andy1621** [comment]
And thanks for your notice, I have uploaded `vqav2_chinese` and `okvqa_chinese` which were not used. I will remove it later in HF.

**Comment by cathyxl** [comment]
hi~@Andy1621 have you uploaded the you cooked videos?

**Comment by Andy1621** [comment]
@cathyxl I have updated the youccok2 videos at the same link. Besides, the `train.json` has been updated since some videos are unable to be read.

Furthermore, I have uploaded the random `train_80k.json` for webvid_caption and `train_100k.json` for coco_caption, which are smaller and lead to similar results. Check them in [hf](https://huggingface.co/datasets/OpenGVLab/VideoChat2-IT).

**Comment by cathyxl** [comment]
Can you pin the link to the youcook2 videos here? I cannot find the link.

**Comment by yinanhe** [comment]
@cathyxl  [aliyun](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/egoqa_split_videos.zip)

**Comment by cathyxl** [comment]
@yinanhe this seems to be a link to ego4d, how about the youcook2?

**Comment by yinanhe** [comment]
I'm sorry for this typo, [this link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/youcook_split_videos.zip) is normal.

**Comment by yinanhe** [comment]
It seems that the issue has been fixed. If you still have any problems, please feel free to reopen this issue.

**Comment by sx1999** [comment]
> Thanks a lot! @Andy1621. Btw, I have the same problem with kinetics710. I found my downloaded video paths of kinetics 400, 600 and 700 cannot match these paths in the 1.9M instruction data. Can you also provide the preprocessing scripts?

hi, I have the same problem with kinetics710, could you tell me how to solve it?

**Comment by Andy1621** [comment]
For those who are interested in YouCook2, I have updated the JSON files in HF.

**Comment by pritamqu** [comment]
> @cathyxl If you downloaded the zip file named "egoqa_split_videos.zip" between `11:00 AM on January 23, 2024(UTC+8)` and `11:00 AM on January 24, 2024 (UTC+8)`, there's no need to re-download it. The videos inside it are for `YouCook`. I'm sorry for this typo, [this link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/youcook_split_videos.zip) is normal now. From now on, the videos in [egoqa_split_videos.zip](https://huggingface.co/datasets/ynhe/videochat2_data/resolve/main/egoqa_split_videos.zip) are the ones for ego4d.

hey the youcook link seems to be broken again - although I find an hf/dataset link here: https://huggingface.co/datasets/ynhe/videochat2_data/blob/main/youcook_split_videos.zip.partab; not sure how to extract from partab, could you please have a look?

**Comment by yinanhe** [comment]
> > @cathyxl If you downloaded the zip file named "egoqa_split_videos.zip" between `11:00 AM on January 23, 2024(UTC+8)` and `11:00 AM on January 24, 2024 (UTC+8)`, there's no need to re-download it. The videos inside it are for `YouCook`. I'm sorry for this typo, [this link](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/videochat2/data/youcook_split_videos.zip) is normal now. From now on, the videos in [egoqa_split_videos.zip](https://huggingface.co/datasets/ynhe/videochat2_data/resolve/main/egoqa_split_videos.zip) are the ones for ego4d.
> 
> hey the youcook link seems to be broken again - although I find an hf/dataset link here: https://huggingface.co/datasets/ynhe/videochat2_data/blob/main/youcook_split_videos.zip.partab; not sure if we can extract from it without other parts, could you please have a look?

@pritamqu  对不起，由于网络问题partaa没有被成功上传，已经重新补了partaa。链接见https://huggingface.co/datasets/ynhe/videochat2_data/resolve/main/youcook_split_videos.zip.partaa  

您需要执行以下的指令来解压压缩包
```
cat youcook_split_videos.zip.part* >> youcook_split_videos.zip
unzip youcook_split_videos.zip
```
