### ISSUE TITLE
Chat Video with Moss  can not related any to video contents?

### ISSUE THREAD

**Issue by CaptainXudui** [OpenGVLab/Ask-Anything#9]
![image](https://user-images.githubusercontent.com/17291290/233877977-dfc680bc-9b21-45a9-9842-2fbe653d9812.png)
  
 I have test some videos including the demo yogo video. The moss chat can not recognize any detail content about video but can talk anyway.
So that is the moss model's fact or anywhere I do something wrong?
Thanks.

**Comment by yinanhe** [comment]
Try to have a conversation with MOSS in Chinese, in our attempt MOSS was able to answer the video related content in a Chinese context even though the information provided was in English

**Comment by yinanhe** [comment]
![image](https://user-images.githubusercontent.com/43169235/233885540-289f46f8-c4d7-4119-b3af-a91f9e2e5252.png)
![image](https://user-images.githubusercontent.com/43169235/233885689-8ce05b6f-32b3-4603-81b7-d5fe27b9eeb6.png)

**Comment by CaptainXudui** [comment]
![image](https://user-images.githubusercontent.com/17291290/233891772-1fd839d9-3207-4704-8bfd-c32e9e931e7e.png)
我用的是moss int4，效果还是不佳

**Comment by CaptainXudui** [comment]
> ![image](https://user-images.githubusercontent.com/17291290/233891772-1fd839d9-3207-4704-8bfd-c32e9e931e7e.png) 我用的是moss int4，效果还是不佳

![image](https://user-images.githubusercontent.com/17291290/233894885-35455387-1d88-4349-9a74-c8feaaab257e.png)
重新多试了几次，效果还可以。

**Comment by CaptainXudui** [comment]
MOSS int4模型可以在3090Ti上很流畅运行，int8模型可以正常部署，但会很快显存不够而溢出。整体来说，moss int4的模型还是可以实现简单的测试。Thanks for sharing~
