### ISSUE TITLE
The version of flash-attention

### ISSUE THREAD

**Issue by LiJiaqi96** [OpenGVLab/Ask-Anything#91]
Hi, when using videochat2 with flash-attention, I encountered an import error that indicates the functions used come from flash-attn v2 rather than 1.0.4 (shown in the requirement.txt).  
  
I tried to install flash-attn v2 with other packages unchanged but failed. Is there any solutions whether I should modify the code or try to install flash-attn v2 with other packages' version? Thanks a lot!

**Comment by Andy1621** [comment]
Hi! Thanks for your reply and sorry for the late response. In my current environment, I use `flash-attn 2.0.9`.

**Comment by LiJiaqi96** [comment]
Thanks for your reply! I will try the flash-attn 2.0.9 and hope it could work

**Comment by LiJiaqi96** [comment]
The issue has been solved by using flash-attn 2.0.9, but remember to update the function name in the code to those in flash attention v2.
