### ISSUE TITLE
Unable to access LLaMA weights to build Vicuna-7B

### ISSUE THREAD

**Issue by muzairkhattak** [OpenGVLab/Ask-Anything#95]
Dear Team,

Thank you for sharing your work for the community. 

I am trying to setup the inference model for videochat but I am having difficulties in downloading the official LLaMA 7b weights as they are not officially available from meta. 

The provided links in below instruction do not provide for LLaMA 1 models. We can only download llama 2 models from below links.

LLAMA: Download it from the [original repo](https://github.com/facebookresearch/llama) or [hugging face](https://huggingface.co/decapoda-research/llama-13b-hf).

Could you upload the llama 7b and llama 13b weights so we can directly utilize it? 

Thank you in advance! 

Kind regards,
Muhammad Uzair

**Comment by yinanhe** [comment]
Bittorrent (magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA).

**Comment by muzairkhattak** [comment]
Thank you !

**Comment by kuaileqipaoshui** [comment]
> Bittorrent (magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA

what is this?

**Comment by muzairkhattak** [comment]
@kuaileqipaoshui you can download the weights directly using the above magnet link via a torrent downloader software.

Alternatively, you can [use this repository](https://github.com/juncongmoo/pyllama) to download LLaMA model weights.

**Comment by kuaileqipaoshui** [comment]
> @kuaileqipaoshui you can download the weights directly using the above magnet link via a torrent downloader software.
> 
> Alternatively, you can [use this repository](https://github.com/juncongmoo/pyllama) to download LLaMA model weights.

thank you!
