### ISSUE TITLE
videochat demo

### ISSUE THREAD

**Issue by kuaileqipaoshui** [OpenGVLab/Ask-Anything#97]
Hello! I ran the videochat .ipynb demo，but got different results.
<img width="648" alt="videochat2" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/cb6f86bd-e2b8-48f6-904f-10caa170ce81">
<img width="640" alt="videeochat1" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/ec82cb18-fdd2-43fa-b5f0-75fff964fadc">

**Comment by Andy1621** [comment]
Hi! As for your question, the answer is not the same since the `do_sample=True`.

**Comment by kuaileqipaoshui** [comment]
> Hi! As for your question, the answer is not the same since the `do_sample=True`.

thanks! I also have a question, that is when I try to run the scripts, an error has occurred.
<img width="506" alt="videochat" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/1ba50197-b1cc-4007-81bf-e0f92d2f8f85">

**Comment by kuaileqipaoshui** [comment]
> Hi! As for your question, the answer is not the same since the `do_sample=True`.

thank you! I'm also trying to run stage1.sh, but I ran into some difficulties.
![videochat3](https://github.com/OpenGVLab/Ask-Anything/assets/137666741/5d91f791-d484-4153-9e70-7e364694d807)
![videochat4](https://github.com/OpenGVLab/Ask-Anything/assets/137666741/4c02bb16-d01a-40fe-90a4-7b473ea5af1e)
Do you know what happened? And how can I fix it?

**Comment by Andy1621** [comment]
It seems that you do not set the right `MASTER_NODE`, the `--rdzv_endpoint` should be one of the running nodes `${MASTER_NODE}:${IP}`.

**Comment by kuaileqipaoshui** [comment]
> It seems that you do not set the right `MASTER_NODE`, the `--rdzv_endpoint` should be one of the running nodes `${MASTER_NODE}:${IP}`.

Thank you. It has been fixed.
