### ISSUE TITLE
video data

### ISSUE THREAD

**Issue by kuaileqipaoshui** [OpenGVLab/Ask-Anything#98]
Excuse me, I encountered some difficulties when I tried to download the webvid-10M dataset. After downloading the csv file, I download the original video in the way he said. it work, but there is nothing in the folder. Is that normal? Or is there any way to handle .csv and .tsv files ? Are downloaded .csv and .tsv files pre-processed into source videos and source pictures?
<img width="627" alt="videochat6" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/58c568db-a453-49e1-80df-19b7390a39d8">
<img width="208" alt="videochat10" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/21216d5e-0e35-4ac5-8384-5c46e2fa4521">
<img width="165" alt="videochat11" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/8e4e94a9-461c-41f6-ac59-025e39dc169b">

**Comment by kuaileqipaoshui** [comment]
I also have a question. What is the difference between webvid and webvid_10m?
<img width="260" alt="videochat8" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/b00adcea-6eac-4b9e-bdaa-92923b7f1137">
And how can I download cc3m and sbu data?
<img width="199" alt="videochat9" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/bd826c29-b954-4f4b-aba0-eaf94b3dd82b">

**Comment by kuaileqipaoshui** [comment]
After downloading the csv file, I download the original video in the way he said. it work, but there is nothing in the folder. Is that normal?
 
<img width="208" alt="videochat10" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/54bf55d3-4210-4736-b18f-00cec0231ced">
<img width="165" alt="videochat11" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/a71c6706-4ce0-4e93-9ee5-10466ae2f649">

**Comment by kuaileqipaoshui** [comment]
<img width="275" alt="videochat12" src="https://github.com/OpenGVLab/Ask-Anything/assets/137666741/52dd8dd7-7ade-4766-a0bf-ea530148ccb1">
Is  "video_image"  the source video data and source image data? What form does 'video_image' take?

**Comment by yinanhe** [comment]
> Excuse me, I encountered some difficulties when I tried to download the webvid-10M dataset. After downloading the csv file, I download the original video in the way he said. it work, but there is nothing in the folder. Is that normal? Or is there any way to handle .csv and .tsv files ? Are downloaded .csv and .tsv files pre-processed into source videos and source pictures? <img alt="videochat6" width="627" src="https://private-user-images.githubusercontent.com/137666741/294644222-58c568db-a453-49e1-80df-19b7390a39d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQyMTUsIm5iZiI6MTcwNDg1MzkxNSwicGF0aCI6Ii8xMzc2NjY3NDEvMjk0NjQ0MjIyLTU4YzU2OGRiLWE0NTMtNDllMS04MGRmLTE5YjczOTBhMzlkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwMjMxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTgxYTlkYWJkOWQyMmI5ZjBlMTI3Y2U3MzNhYWE0ZGE2MjM3NWEzYTY0ZDc2MDRmYzE3YjA5Y2U4NDFmZGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MgvTAB6N_bSafm3-w9P3SuXwlSg-1z7glwQc1S4kFys"> <img alt="videochat10" width="208" src="https://private-user-images.githubusercontent.com/137666741/294685799-21216d5e-0e35-4ac5-8384-5c46e2fa4521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQyMTUsIm5iZiI6MTcwNDg1MzkxNSwicGF0aCI6Ii8xMzc2NjY3NDEvMjk0Njg1Nzk5LTIxMjE2ZDVlLTBlMzUtNGFjNS04Mzg0LTVjNDZlMmZhNDUyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwMjMxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTJhYTIwNTRkYWI2MDE2YzY1MDRlOWRlMDg3ZWUwZGU0YWQyYTM0ZGZmZDk0ODdhZjYyOTZjY2NlYmY0OWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A9KEWTyKbNzV-xKo2_4vLKcVhSyXJtVJsXFJOdPKOHM"> <img alt="videochat11" width="165" src="https://private-user-images.githubusercontent.com/137666741/294685816-8e4e94a9-461c-41f6-ac59-025e39dc169b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQyMTUsIm5iZiI6MTcwNDg1MzkxNSwicGF0aCI6Ii8xMzc2NjY3NDEvMjk0Njg1ODE2LThlNGU5NGE5LTQ2MWMtNDFmNi1hYzU5LTAyNWUzOWRjMTY5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwMjMxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTM3MzFiZWI4YmI5MjlhOWZiMWE2Mzg0YWEzNDMwODkyNWE2ZWY0MGI1Y2RlMzgzYTRkY2MxODlkZTMyYjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.42k-X7T_t5ge4wPU_qWNOjX80h0rvkZ1dOgUqKWc2x0">

I'm sorry for the delayed response. If you have downloaded the original annotation files for webvid, the CSV should contain the download URLs for each video. You can use tools like wget or request to download them, and each folder should have the respective videos, which should not be empty. For specific download details, you can ask in the original repository. The original videos have not been processed into frames or any other preprocessing.

**Comment by yinanhe** [comment]
> I also have a question. What is the difference between webvid and webvid_10m? <img alt="videochat8" width="260" src="https://private-user-images.githubusercontent.com/137666741/294651814-b00adcea-6eac-4b9e-bdaa-92923b7f1137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTIxMDAsIm5iZiI6MTcwNDc5MTgwMCwicGF0aCI6Ii8xMzc2NjY3NDEvMjk0NjUxODE0LWIwMGFkY2VhLTZlYWMtNGI5ZS1iZGFhLTkyOTIzYjdmMTEzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwOTE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjQ1YjczY2ZhZmZkOTE3YzA2YzQ4Y2I3ZGZlN2VkNzM2MTc4OTVhYTU3MWNjNWI4NDc3YjYzYWViMWFlNDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.phrCigFHxyBVee0m0EhEOB5RMW-Wtja2FtZsQsYFlTw"> And how can I download cc3m and sbu data? <img alt="videochat9" width="199" src="https://private-user-images.githubusercontent.com/137666741/294651868-bd826c29-b954-4f4b-aba0-eaf94b3dd82b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTIxMDAsIm5iZiI6MTcwNDc5MTgwMCwicGF0aCI6Ii8xMzc2NjY3NDEvMjk0NjUxODY4LWJkODI2YzI5LWI5NTQtNGY0Yi1hYmEwLWVhZjk0YjNkZDgyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwOTE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzI1NmUxM2I4MDg5ODI3NjE1YWJjNzI3ZjEyYzgxOWUxOWEzNDZkZjU1NTIwM2Y0NmE4ZDNhMGNiNDc0Nzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VbE5-EpuyVnMoWmhzAVel3gNBdDcrVVACbgAsDE25Hs">



> I also have a question. What is the difference between webvid and webvid_10m? <img alt="videochat8" width="260" src="https://private-user-images.githubusercontent.com/137666741/294651814-b00adcea-6eac-4b9e-bdaa-92923b7f1137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTIxMDAsIm5iZiI6MTcwNDc5MTgwMCwicGF0aCI6Ii8xMzc2NjY3NDEvMjk0NjUxODE0LWIwMGFkY2VhLTZlYWMtNGI5ZS1iZGFhLTkyOTIzYjdmMTEzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwOTE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjQ1YjczY2ZhZmZkOTE3YzA2YzQ4Y2I3ZGZlN2VkNzM2MTc4OTVhYTU3MWNjNWI4NDc3YjYzYWViMWFlNDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.phrCigFHxyBVee0m0EhEOB5RMW-Wtja2FtZsQsYFlTw"> And how can I download cc3m and sbu data? <img alt="videochat9" width="199" src="https://private-user-images.githubusercontent.com/137666741/294651868-bd826c29-b954-4f4b-aba0-eaf94b3dd82b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTIxMDAsIm5iZiI6MTcwNDc5MTgwMCwicGF0aCI6Ii8xMzc2NjY3NDEvMjk0NjUxODY4LWJkODI2YzI5LWI5NTQtNGY0Yi1hYmEwLWVhZjk0YjNkZDgyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwOTE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzI1NmUxM2I4MDg5ODI3NjE1YWJjNzI3ZjEyYzgxOWUxOWEzNDZkZjU1NTIwM2Y0NmE4ZDNhMGNiNDc0Nzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VbE5-EpuyVnMoWmhzAVel3gNBdDcrVVACbgAsDE25Hs">

`webvid` refers to WebVid2M, which is a subset of 2.5M. For more details, please refer to [WebVid](https://github.com/m-bain/webvid). You can find the CC dataset on [GitHub](https://github.com/google-research-datasets/conceptual-captions), and the SBU dataset on [GitHub](https://github.com/XuyangSHEN/SBU_Captions_Dataset_Download).
